### ISSUE TITLE
ScreenView should use the 'svg' renderer

### ISSUE THREAD

**Issue by samreid** [phetsims/pendulum-lab#10]
I noticed the main constructor in PendulumLabView.js begins like so:

```js
  function PendulumLabView( pendulumLabModel, mvt, screenshotImage ) {
    var pendulumLabView = this, width, height;

    ScreenView.call( this );
```

However, the ScreenView should specify the svg renderer, like so:

```js
    ScreenView.call( this, {renderer: 'svg'} );
```

This will make it much faster and less fuzzy on retina devices.

**Comment by jonathanolson** [comment]
Looks good, closing.
