### ISSUE TITLE
Typical scenery issues on Firefox

### ISSUE THREAD

**Issue by bryo5363** [phetsims/pendulum-lab#102]
I noticed slight glitching in the gravity and friction box when sliding the slider on FF 38 OSX 10.9.5

**Comment by phet-steele** [comment]
Don't see a problem on macOS 10.12.6 FF. Will check 10.9.5 shortly.

**Comment by phet-steele** [comment]
Don't know what "typical scenery issues" I'm looking for, but FF 53.0.2 on OSX 10.9.5 showed nothing worth fixing.
