### ISSUE TITLE
Oscillation are shown w/ mass @ angle 0

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/pendulum-lab#103]
You can initialize the mass at a very small angle approximately 0.1 degrees, but the sim displays 0 degrees. Oscillation occurs even though the initial conditions state 0 degrees.
(Notice the dotted line for 0 degrees does not line up with the string of the pendulum)
Also even though oscillation occurs the energy graph does not display anything.
![screen shot 2015-06-22 at 11 31 10 am](https://cloud.githubusercontent.com/assets/5631059/8288351/b90f69c4-18d2-11e5-901b-ff3a7a2aef80.png)

**Comment by ariel-phet** [comment]
@arouinfar - perhaps consider adding another decimal point to the angle measurement readout? Not sure if that is appropriate or not. But this seems like a design/pedagogical question not a bug.

**Comment by arouinfar** [comment]
Good observation @orejolaphet.

@ariel-phet, I don't think adding a decimal point is pedagogically necessary. I doubt students would confuse this behavior with a bug, and it could potentially facilitate conversations about rounding and small values. The decimal would also look a bit crowded if we add a second angle readout, as recommended in #95.
