### ISSUE TITLE
Zoom component of Energy graph does not reset

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/pendulum-lab#104]
The scale which you zoom to on the energy graph does not return to default after using the sim reset button.
To reproduce:
Open sim
Select either the "Energy" & "Lab" Screen 
Open Energy Graph
Click Zoom in or out 10+ times
Hit Reset
Open Energy Graph

**Comment by andrey-zelenkov** [comment]
Fixed via https://github.com/phetsims/pendulum-lab/commit/79da8e1db0261faf9f9d275e7ba457c86074afff commit. Reassign to @orejolaphet for verification.

**Comment by orejolaphet** [comment]
Verified fixed in latest commit. Closing.
