### ISSUE TITLE
Friction is always present even when friction is set to none

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/pendulum-lab#105]
Noted in Issue #82

If you zoom in the the energy graph 50+ times you will eventually see some friction in the system during oscillation even though friction is set to none. (Note the smaller the angle the more you must zoom in)

To reproduce:
Open sim
Select seen w/ energy graph
Open energy graph
Click zoom 50+ times
Move mass to large angle and begin oscillation

At small angles
![screen shot 2015-06-22 at 11 57 05 am](https://cloud.githubusercontent.com/assets/5631059/8288933/7864e904-18d6-11e5-914e-503f9c741643.png)

At Large angles
![screen shot 2015-06-22 at 12 00 26 pm](https://cloud.githubusercontent.com/assets/5631059/8288948/8ee480e0-18d6-11e5-9288-f1fefbdc3911.png)

**Comment by orejolaphet** [comment]
Weirdness. If you leave the page for a period of time the friction is no longer displayed.

**Comment by andrey-zelenkov** [comment]
Same behavior you can see for the original Java simulation. It's a feature of selected mathematical model.

**Comment by orejolaphet** [comment]
@ariel-phet what do you think about this behavior?

**Comment by ariel-phet** [comment]
Seems like something we will need to address internally

**Comment by jonathanolson** [comment]
Right now the "thermal energy" is calculated as "total energy - kinetic and potential energy", which causes any inaccuracies and cumulative errors to be added to the thermal energy.

http://www2.phy.ilstu.edu/~rfm/380s13/chapters/CH2.4_Pendulum.pdf notes a differential equation for the change in kinetic/potential energy, which could be approximated on its own at every step.

@ariel-phet, does this seem like a good approach?

**Comment by jonathanolson** [comment]
Reassigning for a response to the above comment.

**Comment by ariel-phet** [comment]
In our discussion I think we agreed on the above approach.

**Comment by jonathanolson** [comment]
Forgot this on my list of things that were fixed by the model updates.
