### ISSUE TITLE
port translations from Flash

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/pendulum-lab#108]
When this is done, also rename any keys with 'tab' prefix to 'screen'.  For example "tab.intro" should become "screen.intro". See https://github.com/phetsims/tasks/issues/353.

**Comment by jonathanolson** [comment]
I believe the decision was to have translation done again. Since there are a number of different strings in the new version, can this issue just be closed?

**Comment by jonathanolson** [comment]
@aaronsamuel137 thought it was fine to have the translators re-do it, so I'm closing this issue.
