### ISSUE TITLE
Property.storeValue will be disappearing

### ISSUE THREAD

**Issue by samreid** [phetsims/pendulum-lab#109]
Property.storeValue will be disappearing due to https://github.com/phetsims/axon/issues/67 .  Pendulum Lab is the only simulation using this method, and it will need to find another way.  Not sure who should work on this, @jonathanolson can you comment?

**Comment by samreid** [comment]
I pushed a proposed fix above and tested it some.  @jonathanolson can you take a look and see if this will work?

**Comment by jonathanolson** [comment]
Looks good to me.
