### ISSUE TITLE
Increase space between mass/length and gravity menus

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#11]
The spacing between the mass/length and gravity menus is crowded, and should be increased. When in two pendulum mode on the Lab screen, the menus will need to be very close, but they do not always need to be this close.

Current dev version:
![image](https://cloud.githubusercontent.com/assets/8419308/5571722/3db7ade0-8f52-11e4-8d69-627b7e2aacfe.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/5571740/632853c2-8f52-11e4-9311-a1c226a8d84b.png)

For comparison, the spacing between the velocity/acceleration and energy graph menus in the current dev version looks good.
![image](https://cloud.githubusercontent.com/assets/8419308/5572563/bee6cdf0-8f5d-11e4-91aa-65e140c31a31.png)

Assigning to @MDmitrieva.

**Comment by andrey-zelenkov** [comment]
Increased space between mass/length and gravity menus. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Looks good. Closing.
