### ISSUE TITLE
Increment value of sliders and tweakers is reversed

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#12]
The tweakers (arrow buttons next to readout) should increment the value in steps of 0.01 and the slider should adjust the value in steps of 0.1. Currently, these are reversed (tweakers are .1 and sliders are .01).

Assigning to @MDmitrieva.

**Comment by andrey-zelenkov** [comment]
Fixed value increment of sliders and tweakers. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
@ariel-phet, can you please verify? I'm not sure that this issue along with #20 are enough to merit another dev version for me to check. Alternatively, I can wait to verify until the next dev version is published.

**Comment by ariel-phet** [comment]
Fixed, closing.
