### ISSUE TITLE
Can step size be a bit smaller?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#122]
I've noticed that stepping forward in dev.6 is very coarse and feels a bit choppy. It was much smoother in dev.5 and allowed users to have more precise control. I'm guessing that performance optimization may have required the step size to become a bit coarser, but is there any way that it could be made a bit smaller @jonathanolson? The step forward button doesn't feel like a very useful feature in its current state.

Pausing the pendulum here (swinging to the left):
![image](https://cloud.githubusercontent.com/assets/8419308/12041836/64c0f20c-ae32-11e5-9682-07472ac14316.png)

Stepping forward 6x:
![image](https://cloud.githubusercontent.com/assets/8419308/12041842/6fd4d47e-ae32-11e5-95e2-880ddac7b33c.png)![image](https://cloud.githubusercontent.com/assets/8419308/12041847/77dad9ac-ae32-11e5-987a-6d5eda5f5142.png)![image](https://cloud.githubusercontent.com/assets/8419308/12041849/80284d1a-ae32-11e5-9a46-3fabc093d93c.png)![image](https://cloud.githubusercontent.com/assets/8419308/12041865/94ea063a-ae32-11e5-849c-218172bb420e.png)![image](https://cloud.githubusercontent.com/assets/8419308/12041874/a3565886-ae32-11e5-93ac-e0b9fd64e00b.png)![image](https://cloud.githubusercontent.com/assets/8419308/12041878/b57e854c-ae32-11e5-9c56-395995adfbcb.png)

**Comment by jonathanolson** [comment]
Switched to the same time interval (50ms) for the step button.

**Comment by arouinfar** [comment]
Thanks @jonathanolson! That feels much better. Closing.
