### ISSUE TITLE
For Energy graph change label to indicate "mass 1" "mass 2"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/pendulum-lab#124]
I think for the energy graph when it is labeled currently "Energy of 2" that could be a bit misleading if read quickly...it appears there is room to say "Energy of Mass 2" and that stays consistent with the labeling of "Mass 1" and "Mass 2" on the sliders.

Seems like an easy change, mind making that @jonathanolson?

**Comment by arouinfar** [comment]
:+1:
