### ISSUE TITLE
"Return" button not clearing thermal energy on graph

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/pendulum-lab#125]
Noticed this problem on 1.0.0-dev.7

 http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.7/pendulum-lab_en.html

Steps to reproduce.

1. Go to energy screen
2. Open energy graph
3. Turn friction to lots
4. Swing pendulum, let some thermal energy accumulate
5. Press return button (not reset, but return), thermal energy will remain

**Comment by jonathanolson** [comment]
It should be a simple fix, but if you return the pendulum (i.e. grab it and move it to the center), wouldn't it maintain its thermal energy?

**Comment by ariel-phet** [comment]
If you grab it and move it...yes. But I consider "return" to mean "return" to the stating condition. This allows you to repeat experiments, but not have to press reset and turn on all the same options. This follows a similar paradigm to GAO and I believe several other sims where we have a button that returns the experiment to the original state but does not "reset" the sim screen.
