### ISSUE TITLE
Edge shows no period trace

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#126]
Each screen will show the trace for the first period (either using Period Trace or Period Timer on the Lab screen), but once the first trace fades away no more will appear. You only see the period trace once a period has finished. Tested on Galileo, and only seen on Edge.

Sorry this gif is so small. In this video I start with mass 1 ready to go and the Period Timer waiting for the mass to start swinging. I press play and the period successfully traces, but any subsequent uses of the Period Timer does not display the trace until the end of the period (page refresh is required to fix):
![edgenotrace](https://cloud.githubusercontent.com/assets/5863899/12854960/f4bc8238-cbf9-11e5-8a62-bd6bb72f35ab.gif)

For phetsims/tasks/issues/498

Troubleshooting information:
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
Features missing: touch
Flags: pointerEnabled, pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1536x747
Pixel Ratio: 1.25/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

**Comment by jonathanolson** [comment]
Also reproducing with rootRenderer=canvas on Chrome.

**Comment by jonathanolson** [comment]
Fixed one Scenery-related bug, but still not fully working. Output drawn in the Canvas looks correct (below), and makes me notice that the slow-motion checkboxes also disappear.

![pendulum-lab-disappeared-1](https://cloud.githubusercontent.com/assets/480878/12896056/11398c3e-ce5d-11e5-946c-615d58844b0a.png)

**Comment by jonathanolson** [comment]
Fixed with Scenery commits.
