### ISSUE TITLE
Period Timer inconsistency between mouse and touch

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#127]
@jonathanolson @arouinfar using a mouse I can click on the little toggle/slider thing to switch between tracing mass 1 and mass 2, but on a touch screen I'm limited to having to touch the little mass images. ...why? I was super confused for awhile why I couldn't switch via touching the toggle until I learned I had to touch the images.

For clarification, I'm talking about this guy:
![pendtimerthing](https://cloud.githubusercontent.com/assets/5863899/12857625/78235c06-cc08-11e5-9d62-3323b332d4ee.PNG)

For phetsims/tasks/issues/498

**Comment by arouinfar** [comment]
Good catch @phet-steele. I think it would be best to have consistent touch and click areas whenever possible.

**Comment by jonathanolson** [comment]
@arouinfar, it also seems like we should potentially make the 2nd mass look disabled when only 1 mass is shown?

**Comment by arouinfar** [comment]
@jonathanolson Yes, that would also be a good idea. Let's try reducing the opacity of the 2nd mass and toggle (if possible) to 50% when in 1-pendulum mode.
