### ISSUE TITLE
Period trace does wrong shape

### ISSUE THREAD

**Issue by BryceAG** [phetsims/pendulum-lab#128]
Test device:
Schrodinger
Operating System:
Windows 8
Browser:
Chrome
Problem description:
When the weights do a full rotation counter clockwise the trace line bends awkwardly. does not happen with clockwise rotation.
Steps to reproduce:
set the pendulum to move, and mess with the gravity until it starts to do full rotations
Severity:

Screenshots:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/15327201/12858858/cfdf8206-cc0f-11e5-9ce7-8a395870dac3.gif)

Troubleshooting information (do not edit):
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1920x971
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

related to phetsims/tasks#498

**Comment by jonathanolson** [comment]
When this occurs, Scenery throws an error:
```
Assertion failed: Not handling arcs with start/end angles that show differences in-between browser handling
```

It's trying to draw an arc with greater than 2pi of a rotation, so it will have browser-specific behavior (thus the weird appearance here).

**Comment by jonathanolson** [comment]
This is related to not fixing https://github.com/phetsims/pendulum-lab/issues/91.

@ariel-phet and @arouinfar, any opinions about interrupting the period trace (and possibly fading out) when the pendulum goes past the vertical line?

**Comment by ariel-phet** [comment]
@jonathanolson I would be fine if we decided to not show the period trace after the pendulum goes past the vertical line.

**Comment by arouinfar** [comment]
@jonathanolson I like @ariel-phet's suggestion. I think it will work nicely, and we'll avoid the issue of showing a period for something that doesn't technically have one.

**Comment by jonathanolson** [comment]
Done, closing.
