### ISSUE TITLE
Acceleration/velocity arrows of 2nd mass remain on screen

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/pendulum-lab#129]
Related to https://github.com/phetsims/tasks/issues/498
Test device: Witten, iPad 2 

Operating System: iOS 9.2

Browser: Safari 601.1

Problem description: When switching from two masses to one masses, the velocity and acc arrows of the 2nd mass will remain frozen on the screen.

Steps to reproduce: select to show velocity and acc arrows. Release two masses then switch back to only viewing one mass. 

Severity:

Screenshots: 
![image](https://cloud.githubusercontent.com/assets/12610678/12895154/1d9f7f24-ce58-11e5-8170-088e31dcb705.png)
![image](https://cloud.githubusercontent.com/assets/12610678/12895155/1dacbaa4-ce58-11e5-8c03-b4c086f39836.png)

Troubleshooting information (do not edit):
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

**Comment by phet-steele** [comment]
@jonathanolson similar issue:

These arrows still remain (for both masses) after a reset all, and re-enabling them. @jonathanolson can you comment if the fix for the original issue would have fixed this, too, or if this is a separate issue?

![pendulumlabarrows](https://cloud.githubusercontent.com/assets/5863899/12931705/4c768c2c-cf3c-11e5-8674-36478de5d30b.PNG)

**Comment by phet-steele** [comment]
@jonathanolson confirmed it's a new issue. There's more to it though in 1.0.0-dev.9, so moving to a new issue.
