### ISSUE TITLE
Energy graph does not reset after Reset All is pressed

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#13]
Test device: MacBook Pro
Operating System: OS X 10.9.5
Browser: Chrome 39.0.2171.95

Problem description:
Pressing the reset all button does not reset the energy graph on the Energy and Lab screens.

Steps to reproduce:
Open up the Energy or Lab screen, drag the pendulum to start motion, and expand the graph.  Press reset all. The energy graph will not reset.

Severity: This needs to be fixed before publishing.

Screenshots:

Before reset all:
![screen shot 2014-12-29 at 3 07 49 pm](https://cloud.githubusercontent.com/assets/8419308/5573621/8e459dc0-8f6c-11e4-8ffc-6e92b4b35ff7.png)

After reset all:
![screen shot 2014-12-29 at 3 07 55 pm](https://cloud.githubusercontent.com/assets/8419308/5573622/8e460d82-8f6c-11e4-96fe-3a7d6d590240.png)

Troubleshooting information (do not edit):
Name: Pendulum Lab
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.1/pendulum-lab_en.html
Version: 1.0.0-dev.1
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Language: en-US
Window: 1048x633
Pixel Ratio: 2.200000047683716/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by andrey-zelenkov** [comment]
Added updating energy graphs after pressing Reset All button. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Issue has been resolved in dev2. Closing.
