### ISSUE TITLE
Positive and negative angle readout behaviour

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#131]
@jonathanolson @ariel-phet Currently, dragging a mass to the left displays angles up to -90 degrees. Dragging further up/left will show the angle value jump to positive 270 degrees followed by decreasing to 180 degrees as the mass continues upward. This is inconsistent with the behaviour of dragging to the right. Dragging to the right shows angles up to 90 degrees, and continues to 91+ degrees as the mass continues to drag.

@arouinfar and I have suggested that the angle readouts behave as following:

Dragging to the left shows values up to -90, and continues up to -179 degrees.
Dragging to the right shows values up to 90 degrees, and continues up to 179 degrees.
When the mass is straight up, the angle will (always) read &plusmn;180 degrees.

**Comment by arouinfar** [comment]
:+1:
