### ISSUE TITLE
Bad touch areas

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#135]
May also be related to https://github.com/phetsims/pendulum-lab/issues/127, although with Chrome's emulation of touch events, I'm still not able to press the AB switch.

**Comment by jonathanolson** [comment]
![pendulum-lab-timer-touch-areas](https://cloud.githubusercontent.com/assets/480878/12900303/d885746e-ce72-11e5-873e-e1388c183e1c.PNG)

**Comment by jonathanolson** [comment]
Updating title to handle all touch-areas, as many are insufficient.

**Comment by veillette** [comment]
I have review the touch areas. Well done. Closing.
