### ISSUE TITLE
?stringTest=double layout issues

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#136]
@jonathanolson @arouinfar Couple of things to note with this screenshot (iPad Air 2, Leibniz):

![img_0034](https://cloud.githubusercontent.com/assets/5863899/12926297/0b093774-cf20-11e5-85b6-be5eba18753c.PNG)

1. An iPad gets VERY cramped with longer strings, especially with the Period Timer out. There's a LOT of unnecessary negative space in each panel that if removed would definitely help un-crowd the screen.
2. The value boxes aren't scaling with longer strings. This wouldn't be a problem if the values were only numerical, but since unit abbreviations that are translatable are included (like "kg" and "m/s^2") this should probably be fixed.

Tested on iOS 9.2 for phetsims/tasks/issues/498

**Comment by phet-steele** [comment]
Troubleshooting information (do not edit):
Name: ‪Pendulum Lab‬:‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html?stringTest=double
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Apple A8X GPU - 75.11.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

**Comment by phet-steele** [comment]
@jonathanolson I hope it goes without saying that ?stringTest=long completely ruins the sim.

**Comment by phet-steele** [comment]
The values for gravity remain unchanged in 1.0.0-dev.9.

![pendulumlabgravityvalues](https://cloud.githubusercontent.com/assets/5863899/12933698/b34f2f3a-cf46-11e5-94ae-eef150db6ccf.PNG)

**Comment by memo330179** [comment]
Assigning to @veillette for review.

**Comment by veillette** [comment]
We have deployed a new dev.10 version. Assigning to @phet-steele for review.

**Comment by arouinfar** [comment]
Took a look at this with @phet-steele. In general, things look good. My one request is that the Period Timer not be allowed to expand its size. The "Period" string has a large font size and plenty of empty space on either side to accommodate large strings without expanding the size of the tool. The same goes for the time readout -- in the unlikely event the "s" gets translated to something a bit longer, there is plenty of room for the string to expand a little, and then shrink down in size.

**Comment by veillette** [comment]
The maximum width of the 'period' title is currently limited to 80% of the width of the period Timer Pendulum Selector (That's the lower third of the period Timer.). This particular string Test double everything including patterns, so this is why the actual  value of the readout gets repeated, even though it is not translatable (only the second is). 

Here is a possible translation
![image](https://cloud.githubusercontent.com/assets/7633344/16656313/325f131c-442c-11e6-80a0-1b5eb774be7f.png)

in comparison, here is the untranslated version

![image](https://cloud.githubusercontent.com/assets/7633344/16656339/4fc96ccc-442c-11e6-937a-30175a56c003.png)

**Comment by veillette** [comment]
Notice how the width of the period timer doesn't change but the aspect ratio does (because the height of the font shrink).

Assigning back to @arouinfar for input and comments

**Comment by arouinfar** [comment]
Thanks @veillette! The long strings you used look good, and I think it's fine if the height shrinks slightly. The motivation for restricting the width was to prevent the timer from becoming overly large.

**Comment by veillette** [comment]
All work is done here. Let's close this issue, and the QA team can open up a new one if something else  shows up.
