### ISSUE TITLE
Gravity menu should open upward

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#14]
The gravity drop down menu should open above the display so it does not hide the slider. It currently opens downward. See screenshots below.

Other formatting issues:
1. The line between the display and the down arrow should be closer to the arrow, so it appears more square (see mockup screenshot below)
2. The size of the drop down menu looks too small for touch. The mocked up version was larger. @jonathanolson, are there general size guidelines the developers use when designing drop down menus for touch?

Current dev version:
![image](https://cloud.githubusercontent.com/assets/8419308/5573743/663f9676-8f6e-11e4-9096-ed62717a6aa9.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/5573738/59b73cce-8f6e-11e4-8d11-7884d1d6335d.png)

**Comment by andrey-zelenkov** [comment]
I have two questions on this issue. 1) In the case of set ComboBox option "listPosition: 'above'" arrow in dropdown menu begins to point upward and I didn't find any option to prevent this (see screenshot). Is it will be ok or should be fixed? 2) How can we change position of planet options list (I've tried translate this node but without success)? I need move it left after scale (see screenshot):

![screen shot 2015-01-13 at 11 06 47](https://cloud.githubusercontent.com/assets/3500611/5717593/7f9a143c-9b14-11e4-94e4-951481fb5ed8.png)

**Comment by arouinfar** [comment]
The vertical size of the box looks good to me. It could be a bit wider to better accommodate future translations (as shown in the mockup screenshot in my first post). I'm not a developer, so perhaps @jonathanolson can answer your technical questions.

**Comment by jonathanolson** [comment]
I don't think there are specific guidelines, generally you want something to be 44px or larger for button-like things (which depends on the screen size in our case).

>  1) In the case of set ComboBox option "listPosition: 'above'" arrow in dropdown menu begins to point upward and I didn't find any option to prevent this (see screenshot). Is it will be ok or should be fixed? 

I feel that the arrow should point upward when the menu opens upward.

> 2) How can we change position of planet options list (I've tried translate this node but without success)? I need move it left after scale (see screenshot)

The stroke looks thicker on the pop-up, which I wouldn't expect (almost like a scaling is being applied to the entire pop-up). Having the entries consist of Text with localBounds overridden like the following allows setting a minimum width for the text, which would presumably keep everything left-aligned:
```js
planetLabel.localBounds = planetLabel.localBounds.withMaxY( Math.min( 200, planetLabel.localBounds.maxY ) );
```
The minimum exists so that we only extend the bounds, and never shrink it.

**Comment by andrey-zelenkov** [comment]
Set listPosition: 'above' for planet labels in gravity menu and added right indent for labels. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
The menu still seems too small for touch. In your earlier screenshot (see below) the vertical height was larger.
![image](https://cloud.githubusercontent.com/assets/8419308/5881559/f3d0d1a0-a2fe-11e4-9181-4476a30988eb.png)

The latest dev version (dev.3):
![image](https://cloud.githubusercontent.com/assets/8419308/5881577/0f782412-a2ff-11e4-885c-c0e0ca26157a.png)

The menu should be taller (like the first screenshot) to better accommodate touch. It was also decided in design meeting that the arrow should continue to point down, even though the menu opens upward.

Reassigning to @andrey-zelenkov

**Comment by andrey-zelenkov** [comment]
Planet menu have made larger but changing of arrow direction requires library improvement. Please reassign this ticket to developers for investigations. Currently reassign to @arouinfar.

**Comment by arouinfar** [comment]
@andrey-zelenkov, can you please include a screenshot of the latest gravity menu?

**Comment by andrey-zelenkov** [comment]
Of course:

![screen shot 2015-01-27 at 11 19 01](https://cloud.githubusercontent.com/assets/3500611/5915397/7b013006-a616-11e4-8258-dd7354de6d76.png)

**Comment by arouinfar** [comment]
Thanks. Menu looks good, closing.
