### ISSUE TITLE
Allow tools to leave dev boundary

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#140]
I've noticed that the stopwatch, ruler, and period timer are restricted to the dev boundary. I think it would be nice to allow these tools to be placed anywhere on-screen, as it would open up the playspace a bit more. We've done this in Bending Light and Charges & Fields. Tools can be placed anywhere on-screen, and will scoot with the browser edge if resized.

**Comment by veillette** [comment]
The three tools can leave the dev boundary but will be scooted back if the browser is resized.

**Comment by phet-steele** [comment]
:+1:
