### ISSUE TITLE
Edge loses some visuals

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#141]
@jonathanolson finding a repeatable procedure for this was tricky and confusing at first, but I managed to simplify it enough:

1. Open the sim to any screen.
2. First slide the Mass 1 mass slider all the way to a max or min.
3. Then slide the Mass 1 length slider all the way to a max or min. Whether you pick max or min, it doesn't have to match your decision in the previous step.
4. Now sliding the mass slider around will cause the left part of the Gravity panel, the left part of the return button, and the single mass button to disappear.

Note that these only disappear if the mass slider is not at a max or min. Once the slider is returned to those positions the issue is not apparent. This gets more complicated to explain when the Mass 2 sliders are made visible as well, but the issue does still happen.

![pendulumlabcroppedpanel](https://cloud.githubusercontent.com/assets/5863899/12928751/8739085e-cf2c-11e5-8769-406f5a3756bd.PNG)

Tested on two personal Win 10 computers to verify it's not a hardware issue. For https://github.com/phetsims/tasks/issues/498.

Troubleshooting information:
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1600x746
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

**Comment by jonathanolson** [comment]
I can reproduce this off 1.0.0-rc.8, but not from master. Can you test on phettest to see if master has the problem?

I may have fixed this by fixing a different Canvas bug.

**Comment by phet-steele** [comment]
@jonathanolson I can't reproduce on master either.

**Comment by jonathanolson** [comment]
Ok, closing. Reopen if it occurs again in next dev version.
