### ISSUE TITLE
Graph doesn't update until mass translates

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#143]
@jonathanolson pretty self explanatory. Pause the sim with the energy graph open. Move some variables around and the energy bars won't update until the mass moves (press play or drag it). Note this is entirely possible without pausing the sim by means of multitouch (holding the mass in place with one finger, changing things with another).

Tested on Win 10 Chrome and iPad Air 2 (Leibniz). For phetsims/tasks/issues/498.

Troubleshooting information:
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

**Comment by memo330179** [comment]
Assigning to @veillette for review.

**Comment by veillette** [comment]
Assigning to @phet-steele

**Comment by phet-steele** [comment]
Looks fixed to me.
