### ISSUE TITLE
Vectors aren't affected by Reset All

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#144]
Discovered while exploring #129.

1. Starting with both Velocity and Acceleration vectors checked, and with both masses swinging, reset the sim.
2. Re-enable both vectors:

![pendulumlabarrows2](https://cloud.githubusercontent.com/assets/5863899/12934080/3b610356-cf49-11e5-98ae-80f68b4a6e98.PNG)

Notice that the Velocity vector for Mass 2 is missing (trust me it's Mass 2!). Switching to 2 mass view magically makes that vector appear:

![pendulumlabarrows3](https://cloud.githubusercontent.com/assets/5863899/12934117/84a4d998-cf49-11e5-96d1-d0e2a5c941a4.PNG)

This was seen in 1.0.0-dev.8, but the missing arrow (second screenshot) issue I only see in 1.0.0-dev.9. Tested on Win 10 browsers and iPad Air 2 (Leibniz). Sort of maybe possibly perhaps for phetsims/tasks/issues/498.

Troubleshooting information:
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.9/pendulum-lab_en.html
Version: 1.0.0-dev.9 2016-02-09 22:54:31 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Language: en-US
Window: 1600x767
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"a669ea6a","branch":"master"},"babel":{"sha":"1f0156c5","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"75703f39","branch":"master"},"dot":{"sha":"0cb241da","branch":"master"},"joist":{"sha":"439bf5a8","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"69e6f1d8","branch":"period-timers"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"8a58e6f4","branch":"master"},"scenery-phet":{"sha":"b029ebc0","branch":"master"},"sherpa":{"sha":"e75c3756","branch":"master"},"sun":{"sha":"ddc2051e","branch":"master"},"tandem":{"sha":"a2834868","branch":"master"}}

**Comment by veillette** [comment]
velocity and acceleration arrows are updated when the visibility is toggled (instead of assuming it was), I'll leave this open and you can close it when the new dev is issued

**Comment by phet-steele** [comment]
:+1:
