### ISSUE TITLE
?stringTest shenanigans

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#145]
@jonathanolson no idea what I'm seeing here, check it out:

The normal panel:
![pendulumlabnormal](https://cloud.githubusercontent.com/assets/5863899/12961506/0d5cf2fc-cffe-11e5-91e6-f9b1ba825bb7.PNG)

Panel with ?stringTest=double (behaves as expected):
![pendulumlabdouble](https://cloud.githubusercontent.com/assets/5863899/12961522/27c87ac6-cffe-11e5-87f4-a121aebda1e7.PNG)

**BUT** using any of our other string tests (rtl, long, etc..) or even just some random value, like "h", does this:
![pendulumlabh](https://cloud.githubusercontent.com/assets/5863899/12961540/4b9406e6-cffe-11e5-95ef-5dbeff662b35.PNG)

Where did all the strings go? The tweaker & values, "None", "Lots", and the entire slider are completely replaced. What? I've so far seen this on Win 10 browsers, on 1.0.0-dev.8. For phetsims/tasks/issues/498.

Troubleshooting information:
Name: h
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.8/pendulum-lab_en.html?stringTest=h
Version: 1.0.0-dev.8 2016-02-03 23:48:40 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"3a5c7fb6","branch":"master"},"babel":{"sha":"cb55342f","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"38916c91","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"pendulum-lab":{"sha":"07b907c0","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"d0753b38","branch":"master"},"scenery-phet":{"sha":"f02afc1a","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"sun":{"sha":"36a0486f","branch":"master"},"tandem":{"sha":"bfd87e0e","branch":"master"}}

**Comment by jonathanolson** [comment]
Fixed. Was caused by the original authors sidestepping recommendations for the body enumeration, and passing/comparing the actual translated strings of bodies (e.g. "Earth"). And adding extra code to look up a body by its translated string. Yup.
