### ISSUE TITLE
Dynamic layout jiggles system sliders for short translations of "None" and "Lots"

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#146]
If set with a stringTest of a single character, the slider thumb extends past the labels, and the layout can cause the slider's horizontal position to jiggle if you alternate between min/max.

**Comment by memo330179** [comment]
Commit 508a433 should fix this.

**Comment by memo330179** [comment]
Assigning to @veillette for review.

**Comment by veillette** [comment]
This works. closing
