### ISSUE TITLE
Scaling of pendulum's length does not match design document.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/pendulum-lab#148]
According to the design document the version dev.9 of the Pendulum lab does not satisfy this mock-up.

**Current Version**

![image](https://cloud.githubusercontent.com/assets/13894380/16151505/5f67497c-346b-11e6-8646-8e4dd0a58dfb.png)

**Mock-up**
![image](https://cloud.githubusercontent.com/assets/13894380/16151406/d6d18ece-346a-11e6-86cb-898debfa1ddb.png)

This will require scaling of the ruler as well.

**Comment by veillette** [comment]
Assigning to @arouinfar for feedback.

**Comment by veillette** [comment]
In consultation with @ariel-phet , we reverted the change  to the length of the reuler and the range of the pendulum lenth to match dev9. Closing
