### ISSUE TITLE
Period Timer tool missing highlight

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#15]
The Period Timer is missing the highlight on the upper left corner (as shown in mockup).

Dev version:
![image](https://cloud.githubusercontent.com/assets/8419308/5573966/41cc8bf6-8f72-11e4-956a-3dcc6421d280.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/5573977/64552b4c-8f72-11e4-9b36-d9df16e606b8.png)

**Comment by andrey-zelenkov** [comment]
I have a question on this issue. Is it possible to make the highlight using some the library components, or it should be done using a linear gradient only?

**Comment by arouinfar** [comment]
@jonathanolson can answer this question.

**Comment by jonathanolson** [comment]
To reproduce the desired look, you could use a linear gradient along the top, with a radial gradient on the left (with the same color stops).

**Comment by andrey-zelenkov** [comment]
Added highlight for Period Timer tool. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Looks good. Closing.
