### ISSUE TITLE
Period Timer Play Button Icon Functionality

### ISSUE THREAD

**Issue by Denz1994** [phetsims/pendulum-lab#150]
The Period Timer's play button does not follow the design doc as follows:

The design doc specifies that the play button icon changes when the period trace starts.

![image](https://cloud.githubusercontent.com/assets/13894380/16424811/b7e7d568-3d2f-11e6-8c25-d684d45d49b3.png)

Currently the icon changes when the button is pressed. It changes from the triangle icon to the u-turn arrow image immediately after the button is pressed and not when the trace starts.

![image](https://cloud.githubusercontent.com/assets/13894380/16424604/e13b0e04-3d2e-11e6-9e03-9555ebeea7d9.png)               ![image](https://cloud.githubusercontent.com/assets/13894380/16424978/5ce9c274-3d30-11e6-9c1a-19de428e82cd.png)

This issue is only being raised because the play icon doesn't follow the design doc as specified, however the timer does work. In its current state the immediate change of the icon allows users to note that the timer has changed its state, but we wanted to make sure this wasn't an oversight in implementation.

**Comment by arouinfar** [comment]
Good observation @Denz1994! Originally, the behavior was designed to follow the Flash version, but the current implementation is more desirable. Depending on the pendulum's speed, it may take a little while before it crosses the midline and the period starts recording. In that case, having the immediate feedback of the play button turning into the reset button lets the user know that their original click "went through". 

Generally speaking, the design doc may not always be up-to-date once development begins, as design changes are requested and discussed on GitHub. If you encounter a discrepancy between the design doc and the latest dev version, chances are there is a GitHub issue where a change request was made (though there are exceptions).
