### ISSUE TITLE
Second pendulum starts off screen

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/pendulum-lab#152]
For phetsims/tasks#632
Test device: Galileo

Operating System: Win 10

Browser: Chrome

Problem description: On any of the screens, when you select 2 pendulum view, the second pendulum will initialize to having a length of 1.5m which is hanging off screen, making it impossible to drag the mass until you adjust the length slider. After you drag the slider, it will then go back to normal behavior with 1m being the maximum length. As far as I can tell, this only happens after the Reset All button has been used at least once. (It will behave as it should, starting at 1m, if you select 2 pendulums before ever using the Reset All button. Only after resetting does the problem occur.)

Steps to reproduce: Open the sim to any screen, click Reset All, then select 2 pendulums.

Screenshots:
![pendulum-lab](https://cloud.githubusercontent.com/assets/11947677/16469429/20dfbf20-3e0e-11e6-8f54-7b737e054515.PNG)

Troubleshooting information (do not edit):
Name: ‪Pendulum Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.11/pendulum-lab_en.html
Version: 1.0.0-dev.11 2016-06-29 18:50:32 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1920x971
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 9 uniform: 253
Texture: size: 16384 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"0ce3b9c8","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"8b0e56b0","branch":"master"},"dot":{"sha":"8782eeac","branch":"master"},"joist":{"sha":"fa5db70c","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"pendulum-lab":{"sha":"9521f5f5","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"4476eb95","branch":"master"},"scenery-phet":{"sha":"6de9c366","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"0d7e743b","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"}}

**Comment by veillette** [comment]
We failed to correct that cruft from dev.10. thanks for pointing it out.

**Comment by veillette** [comment]
Closing
