### ISSUE TITLE
Increase size of pendulums and vectors in navbar icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#153]
@ariel-phet pointed out that the navbar icons for the Intro and Lab screens are a little hard to interpret.
![image](https://cloud.githubusercontent.com/assets/8419308/16497757/d4de825c-3eb5-11e6-8085-843f063f5545.png)

Self-assigning this issue to update the artwork for the icons. The size of the pendulums and vectors should be exaggerated a bit.

**Comment by arouinfar** [comment]
I've exaggerated the Intro and Lab screen navbar icons (bottom)
![image](https://cloud.githubusercontent.com/assets/8419308/17578909/41068d9c-5f4c-11e6-9c30-7a80882c2841.png)

The modified icons look a bit more recognizable in context
![image](https://cloud.githubusercontent.com/assets/8419308/17578932/763a08fe-5f4c-11e6-9792-f438eedb52aa.png)

Here are the updated image files. These should be used in the navbar only -- no need to change the home screen icons.
[lab_navbar_icon.png](https://cloud.githubusercontent.com/assets/8419308/17579004/6552f2ac-5f4d-11e6-8eb8-aa9713b8f38c.png)
[intro_navbar_icon.png](https://cloud.githubusercontent.com/assets/8419308/17579003/654f7514-5f4d-11e6-852a-419067e90858.png)

Assigning to @veillette for implementation. Please let me know if you need an .ai file for this.

**Comment by veillette** [comment]
![pendulum lab screenshot](https://cloud.githubusercontent.com/assets/7633344/17593361/9f272bb8-5fb3-11e6-8066-140403eac9c9.png)

Thanks @arouinfar, the two navbar icons have been added. I updated the license file for the images and added you to the credits. 

The sim builds with brand=phet without complaint.


Closing

**Comment by veillette** [comment]
![image](https://cloud.githubusercontent.com/assets/7633344/17607958/3a2bcafe-5ff7-11e6-9ea4-be9ba6928f88.png)

We are hitting an assertion.  The intro-navbar-icon does not  have a correct aspect ratio.
It size is 1133/778= 1.45629820051

```
        var validAspectRatio = Math.abs( iconAspectRatio - navbarIconAspectRatio ) < tolerance || Math.abs( iconAspectRatio - homeScreenIconAspectRatio ) < tolerance;
        assert && assert( validAspectRatio, 'NavigationBar icons for screen ' + screenIndex + ' did not have a valid aspect ratio.' );
```

The tolerance is 0.001

FYI, the icon must be a minimum of 147x100 and have an aspect ratio of 548/373=1.469.  See https://github.com/phetsims/joist/issues/76

**Comment by veillette** [comment]
And there is a similar problem with the intro-navbar-icon :(

**Comment by veillette** [comment]
Assigning to @arouinfar to reissue new icons,

**Comment by arouinfar** [comment]
Let's try these @veillette. I resized them to 441x300.

[intro_navbar_icon.png](https://cloud.githubusercontent.com/assets/8419308/17631805/cca19716-6082-11e6-880c-d2e4f58a0106.png)
[lab_navbar_icon.png](https://cloud.githubusercontent.com/assets/8419308/17631806/ccc0c1b8-6082-11e6-9abb-6d5ff5a36d40.png)

**Comment by veillette** [comment]
Thanks @arouinfar , the new icons do not trigger assertions, and the branded sim builds without errors as well. 
Closing.

**Comment by arouinfar** [comment]
Master looks good! Thanks @veillette.
