### ISSUE TITLE
Start/Reset button on Period Timer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#16]
After recording one full period, the reset button on the period timer should switch back to the start button. The reset button should only display while the period timer is in operation.

Before recording:
![image](https://cloud.githubusercontent.com/assets/8419308/5574004/d7944138-8f72-11e4-813e-e3872e2cce22.png)

During recording:
![image](https://cloud.githubusercontent.com/assets/8419308/5574010/f989f2f6-8f72-11e4-9e38-22d363fe50fe.png)

After recording:
![image](https://cloud.githubusercontent.com/assets/8419308/5574008/e5070f94-8f72-11e4-810f-6fcc6232cb10.png)
The start (play) button should now be displayed because the timer is ready to record again.

**Comment by andrey-zelenkov** [comment]
Added switch back reset button on the period timer to the start view after recording one full period. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
This issue has has been fixed in dev2. Closing.
