### ISSUE TITLE
Pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#165]
Reviewed the latest dev with @jonathanolson this afternoon to discuss pixel polishing. I have a handwritten list on my desk, so self-assigning myself so I remember to convert it to a checklist tomorrow morning.

**Comment by arouinfar** [comment]
**Colors**
- [ ] Update panel color a light gray
- [ ] Change Length and Mass strings to black
- [ ] Hover color of mass and length slider thumbs should be a brighter red/blue rather than the default turquoise

**Sizing**
- [ ] resetAllButton should be its normal size
- [ ] Reduce size of all checkboxes and radio buttons to roughly match the height of string
- [ ] Font size of strings next to checkboxes, radio buttons, "Energy Graph", and slider titles should all be the same (this might be the case already, but double check)

**Alignment**
- [ ] Panels should have a 10 px padding with the edge of dev boundary (or window edge when floating) and there should be 10 px between panels
- [ ] Bottom align scene selection with toolbox panel and resetAllButton, but maintain relative alignment of scene selection, play/pause, normal/slow
- [ ] Return button should be center-aligned with resetAllButton and left-aligned with the Gravity panel.
- [ ] Move vector icons to the right so that there is ~10px padding between the point and right edge of the panel
- [ ] On Intro, left align default position of Ruler with the toolbox panel
- [ ] Left alight "Friction" with "Gravity"

**Energy Graph**
- [ ] Height of Energy graph should be consistent on Energy and Lab screens.
- [ ] Maximize the height of Energy Graph between vector and toolbox panels
- [ ] @arouinfar will open a separate issue to add info button/legend so labels can be shortened

**Period Timer**
- [ ] Reduce overall size by 15%
- [ ] Reduce the thickness of the black border (or make yellow rectangle bigger)

**Misc**
- [ ] Change "Slow Motion" to "Slow"
- [ ] Add horizontal dividing line between pendulum 1 and pendulum 2 controls, similar to those used on the [Lab screen](http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.7/projectile-motion_en.html?screens=4) of Projectile Motion

I can also make some recommendations for the spacing in the length/mass and gravity/friction panels, but I'd like to see how much space the alignment tweaks will buy us.

**Comment by jonathanolson** [comment]
> Height of Energy graph should be consistent on Energy and Lab screens.

Then what is the desired behavior for its position? Currently on the Energy screen, it is top-aligned.

I was imagining the energy graph would be sized on each screen to fit nicely between the top and the tool checkbox panel.

Instead it sounds like we need to decide to keep the graph on the top (on the Energy screen), or on the bottom?

**Comment by jonathanolson** [comment]
> Move vector icons to the right so that there is ~10px padding between the point and right edge of the panel

Is this describing moving these icons to the right?:
![pendulum-vectors](https://user-images.githubusercontent.com/480878/28232632-002d04fa-68af-11e7-93ab-e8793bd926d1.PNG)

**Comment by arouinfar** [comment]
>  is this at a non-standard aspect ratio for a reason, or can I set it to the standard one and rework the sim to fit?

There is NO reason why the sim should be at a non-standard aspect ratio. Please use the standard size @jonathanolson.

> Then what is the desired behavior for its position?

My original thought was that the height would be defined by the amount of space available on the Lab screen, and it would be the same size on the Energy screen. However, it sounds like the height can be defined by how much available space there is on each screen? If that's the case, then I think it would be nice to allow for a taller Energy Graph on the Energy screen (top of screen down to toolbox panel) and scale it down a bit to fit the space between the vectors and toolbox on the Lab screen. 

> Is this describing moving these icons to the right?:

👍

**Comment by jonathanolson** [comment]
I believe all of the relevant changes have been made, so I'd love to get feedback on the current version (published http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.13/pendulum-lab_en.html so it would be easy).

What further tweaks should be made?

**Comment by arouinfar** [comment]
@jonathanolson overall things are looking really good! A few more things

- [ ] Energy Graph open by default on Energy screen, closed by default on Lab screen.
- [ ] Widen Mass & Gravity panels by 25 px so Gravity and Friction slider tracks can be a bit longer. They currently feel a bit too short.
- [ ] Gravity readout/tweakers could use more vertical padding. Increase padding on either side by 5px (and move Friction control down 10 px to accommodate the change).

**Comment by jonathanolson** [comment]
Implemented those three changes, let me know how they look.

**Comment by arouinfar** [comment]
Looks good @jonathanolson! When I requested for the Friction control to be moved down 10 px, my thinking was that giving the readout extra padding would reduce the padding between Gravity thumb and Friction title. I'd like to keep the same relative spacing between the thumb on the Gravity slider and the Friction title, so can you move the Friction controls back up? 
![image](https://user-images.githubusercontent.com/8419308/28728052-61689d30-7384-11e7-8771-ff3cf2886fa8.png)

**Comment by jonathanolson** [comment]
Ok, reverted the extra space between the "gravity controls" and "friction controls". Sorry about that!

Let me know if that looks good, and if there are any other related changes.

**Comment by arouinfar** [comment]
Thanks, looks great! I don't have any further requests @jonathanolson.
