### ISSUE TITLE
Independent zooming

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#166]
Currently, it seems like the zoom in the energy graph for the first and second pendulum is independent. Seems weird to me, as you can adjust zooms so one looks huge, and one looks tiny (and there is no indication of zoom differences when switching back-and-forth).

Is this something that would need to change?

**Comment by arouinfar** [comment]
That also seems weird to me @jonathanolson. Can you update the behavior so that the zoom is consistent across both?

**Comment by jonathanolson** [comment]
Will do.

**Comment by jonathanolson** [comment]
Fixed in the above commit.
