### ISSUE TITLE
Add legend to energy graph

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#168]
To maximize the amount of available vertical space, abbreviate the labels in the Energy graph and add a legend dialog, similar to Masses and Springs.
![image](https://user-images.githubusercontent.com/8419308/28227676-4535e902-6898-11e7-9bca-f3b4b30aa937.png)
![image](https://user-images.githubusercontent.com/8419308/28227688-5424b808-6898-11e7-91ad-306539628ba6.png)

Self-assigning to mock up.

**Comment by arouinfar** [comment]
@jonathanolson here's a mockup of the Energy Graph with the info button (uses font awesome [fa-info-circle](http://fontawesome.io/icon/info-circle/)) and the Energy Legend dialog. The zoom buttons differ slightly from master, but that is unintentional. 
![image](https://user-images.githubusercontent.com/8419308/28646224-e642699a-721d-11e7-96e8-890726d11483.png)

![image](https://user-images.githubusercontent.com/8419308/28646215-d711ff08-721d-11e7-9499-14097bc7750a.png)

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks.

**Comment by arouinfar** [comment]
Love it @jonathanolson! The only issue is that the close button appears to be out of bounds:
![image](https://user-images.githubusercontent.com/8419308/28735516-c8e7c1ac-73a2-11e7-8207-2c7277965efd.png)

**Comment by jonathanolson** [comment]
I pushed a common-code fix to joist in https://github.com/phetsims/joist/issues/346, can you try pulling common repos and retesting?

**Comment by arouinfar** [comment]
Thanks for the clarification. Will do @jonathanolson.

**Comment by arouinfar** [comment]
Much better now! Thanks @jonathanolson!
