### ISSUE TITLE
Period trace draws outside of bounds

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#17]
When the pendulum reaches the maximum displacement, the period trace draws outside of the pendulum's path. Instead, the trace should follow the pendulum's string. See the screenshots of the mockup and original sim for an example.

Dev version with period trace outside of bounds:
![image](https://cloud.githubusercontent.com/assets/8419308/5574388/0805a930-8f7b-11e4-94cb-8771846f7613.png)
 
Mockup:
![image](https://cloud.githubusercontent.com/assets/8419308/5574440/76fa1028-8f7c-11e4-9ac9-8369103f10e1.png)

Original sim:
![image](https://cloud.githubusercontent.com/assets/8419308/5574484/7f73859e-8f7d-11e4-8c13-9fa34d06892b.png)

**Comment by andrey-zelenkov** [comment]
Fixed period trace drawing. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Looks good. Closing.
