### ISSUE TITLE
Refinements to Period Timer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#171]
The size of the period timer was reduced in #165 but it still feels a bit off to me. Self-assigning to play around with the mockups.
![image](https://user-images.githubusercontent.com/8419308/28234256-dbc5cf00-68ba-11e7-84a2-cde69c645c92.png)

**Comment by arouinfar** [comment]
I've been cleaning up the Period Timer a bit, and have arrived at a design I'm happier with. 
![image](https://user-images.githubusercontent.com/8419308/28645774-0d286d36-721c-11e7-8707-852b49e9f4bf.png)


Here it is in context next to the current period timer.
![image](https://user-images.githubusercontent.com/8419308/28645811-2ad12da0-721c-11e7-9967-af935aa8513f.png)



Proposed changes:
* Reduced black border
* Softer gradient on the mass icons
* Reduced overall size (110x75) and adjusted aspect ratio
* Font size 12pt
* Changed background color to #ffd56e (more complementary to the blue)

@jonathanolson should I send you an asset for the tool background and each of the mass icons?
![image](https://user-images.githubusercontent.com/8419308/28645995-b9d87fa8-721c-11e7-8194-1ddaf1e3faf3.png)

**Comment by jonathanolson** [comment]
> should I send you an asset for the tool background and each of the mass icons?

Yes for the tool background. Additionally, I'd like to know (@ariel-phet maybe?) if this type of border will want to be used for other sims, as I have two options:

- Just use the fixed-size image for now (best if it's just for this sim)
- Chop it up into corners/edges, and make it like an alternative Panel style (so it can resize nicely, and could be easily reused in other sims)

I'll be fine with either choice.

For the mass icons, I'd prefer to generate those in code.

**Comment by arouinfar** [comment]
> For the mass icons, I'd prefer to generate those in code.

👍

> Additionally, I'd like to know (@ariel-phet maybe?) if this type of border will want to be used for other sims

This border is already used in CCK. The voltmeter and non-contact ammeter have a similar design, but the bodies aren't rectangles. Not sure if your proposed generalization would apply to rectangular bodies only @jonathanolson.
![image](https://user-images.githubusercontent.com/8419308/28727609-b98f2468-7382-11e7-832b-531b6144fb92.png)

**Comment by jonathanolson** [comment]
> Not sure if your proposed generalization would apply to rectangular bodies only

Rectangular bodies only was my thought.

It would be possible still to generate a '3d' look like this in code, but it would be a bit more complicated (e.g. make a piecewise continuous function that is the "height" of the "rubberized" 3d part per pixel location, then shade it based on computing the normal vector and a light direction).

If we ever want more-realistic looking components, I'd encourage we look into that approach (which isn't too crazy, but is more work).

**Comment by ariel-phet** [comment]
@jonathanolson I was going to mention CCK, but I think for now it would be best to just use the image. Besides CCK no sims on the horizon with this style. We can revisit if one comes up.

**Comment by arouinfar** [comment]
Thanks for your input @ariel-phet. I've sent the assets for the Period Timer to @jonathanolson.

**Comment by jonathanolson** [comment]
Implemented, can you see if this appearance needs any changes?

**Comment by arouinfar** [comment]
I like it! Thanks @jonathanolson.
