### ISSUE TITLE
other language json

### ISSUE THREAD

**Issue by MohamadSH** [phetsims/pendulum-lab#172]
Hi ,sorry if it is not the right place for this question .  I didn't find any support-like section to put this .
I see every simulation on the project's website is available in so many languages . My problem is that I can't find the translation of my language for any of simulations in their repositories.
I need to have some of your simulation source code along with translation files. Is that possible ?

**Comment by veillette** [comment]
Thanks for your comment @MohamadSH. At PhET we strive to get our simulations translated in as many languages as possible. All simulations produced by PhET can easily be translated. The translated simulations in a particular language can be found at https://phet.colorado.edu/en/simulations/translated.  The translation process is done by a team of volunteers across the world. 

If a particular simulation is not translated, you can help out by becoming a translator! There is no need for any programming skills.  The translation process for the HTML5 and the Java/Flash simulations is slightly different. For the older flash and java simulations, there is a translation utility that has been developed to help. For the HTML5 simulations, the translation process can be carried out within a browser. If you are interested please contact phethelp@colorado.edu for more information.

The webpage for translators can be found at https://phet.colorado.edu/en/for-translators

**Comment by veillette** [comment]
For your information all the translated strings for the HTML5 simulations are kept in the repository https://github.com/phetsims/babel

However it is easier to commit the translated strings through our webBrowser utility than do it manually.

**Comment by MohamadSH** [comment]
Thank you very much for this very helpful information.
I've been looking at translation files and also your source codes for a some hours. 
It will be my pleasure to participate in complete the translation of this amazing project to my own language but at the moment I'm working on integrating the translated ones with an educational website and if I did this , the result will be having so many students from my country using your amazing sims for free. 
Currently the only problem is that I can't run any of these in my own language . I have cloned all of source codes and dependencies and translations to a server and I can run them in English very easily but I have not been able to find the line or file where I can choose the language of the sims . I thought it should be in a config file or something . but apparently it is not. Could you please help me with this?

**Comment by veillette** [comment]
Although we would prefer that you translate directly with our utility, it is possible to build the simulations manually from the master branch. I should warn you that the master branch is unstable and therefore can introduce bugs/issues that have not been addressed in our published versions. 

For instance, if you would like to build a version of pendulum-lab in french.

First you would need to ensure that within the directory phetsims\babel\plinko-probability, there is a file named
plinko-probability-strings_fr.json

If the file does not exist for your locale, you can modify another locale and give it the proper filename.

Within the directory  phetsims\chipper, you should issue the command 
 ```
npm install
```

Within the directory  phetsims\plinko-probability, you should issue the command 
 ``` 
npm install

grunt build --locales=fr
```

The build file will be generated within a subdirectory named build of plinko-probability.

If you cannot run the task manager, it may be because you have not installed the grunt client or the node package manager.  The html5 development guide has some information on how to proceed.
https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit

**Comment by MohamadSH** [comment]
Thank you very much for the help,
I understand the easiness of using your utility which I suppose you mean downloading my language version of the simulation on your website and serving it on my server.
This is fine . The only problem would be low performance . Because what we download on the website are basically some html files which involve all of the necessary libraries and java codes. I suppose serving an HTML file of over 1 megabytes is not a really good way. Don't you think so?

**Comment by veillette** [comment]
As part of our effort, we provided the opportunity the entire website. In our deployment process,  we can then generate a version of the website in your locale  (see https://phet.colorado.edu/fr/simulations/category/html for the french version )

In addition,  a build version of all the simulations is provided in all locales such that you can use them for offline access or to host them on a separate server (see  https://phet.colorado.edu/fr/offline-access for the french version)
The build process is automated for all locales and therefore generate simulations that are as up to date as the english version.

**Comment by MohamadSH** [comment]
The first link is exactly what I talked about . I mean in that way we have to serve a large HTML file on our server.
But the second link which I had not found about, is absolutely amazing and I can't thank you enough for this very valuable information . I think the best way to host simulations on a Linux server would be installing the whole package on it and then make it available for everyone. 
The only issue I faced is installing the binary file. I downloaded the `bin` file (appropriate for Linux) and I tried to install it through SSH but after running the command it looks like nothing gets executed. It prints out no system messages or scripts or anything! It looks like nothing has been added to the /bin folder or anywhere else. Is it normal ? I don't think there is something wrong with the bin file.
What exactly is going to happen after installing this file? I supposed it was going to do something like extracting all the files in to a directory. Is that true?

**Comment by ariel-phet** [comment]
@MohamadSH you should probably email us (phethelp@colorado.edu) with further questions regarding translation

If you want our sims on an educational website, you could consider simply embedding them. The advantage of embedding them is you then are always guaranteed the latest version, so bug fixes/updates/latest translations are assured.

**Comment by MohamadSH** [comment]
Excuse me for posting my questions in here. I will be contacting you through the email you mentioned . Thank you very much for your patience.

**Comment by ariel-phet** [comment]
@MohamadSH no problem, we appreciate communication with our community!
