### ISSUE TITLE
Period Timer should reset when stop button pressed

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#176]
In verifying #173, I noticed that the Period Timer is still in "Record Mode" if the stop button is pressed mid-recording. The timer will return to zero, but the reset button will be active, like this:
![image](https://user-images.githubusercontent.com/8419308/29043778-dc9202d8-7b79-11e7-8f02-37ec1f9a92e1.png)

If the pendulum is displaced again, the period timer will immediately start recording the period.

This behavior seems a bit odd to me, and I think it would make more sense if the period timer aborted its recording and returned to this state when stop is pressed.
![image](https://user-images.githubusercontent.com/8419308/29043967-756412da-7b7a-11e7-9157-f3c606fafbbc.png)

**Comment by jonathanolson** [comment]
Fixed, can you verify?

**Comment by arouinfar** [comment]
👍
