### ISSUE TITLE
Period Timer continues measuring when disabled

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#177]
1. Lab screen, enable the Period Timer.
2. Use Slow Motion so this is easier, if you want.
3. Get the mass swinging and start the Period Timer.
4. Before the trace has finished drawing, uncheck the Period Timer.

You will still see the trace end, then start again at the next period. In situations where the mass makes a complete revolution, the trace will continuously be drawn (which would be fine IF the timer were enabled).

![pl01](https://user-images.githubusercontent.com/5863899/29136597-fae93f08-7cfa-11e7-86e4-f411e5e51cbf.gif)

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/34.

URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.14/pendulum-lab_en.html
Version: 1.0.0-dev.14 2017-08-07 21:27:47 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"2dc0e278","branch":"master"},"babel":{"sha":"f4b82ef6","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"65b58c78","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"6e8a3c5f","branch":"master"},"kite":{"sha":"dc5c4382","branch":"master"},"pendulum-lab":{"sha":"cc60181b","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"6060a0d7","branch":"master"},"scenery-phet":{"sha":"37bf8502","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"a1b4c71c","branch":"master"},"tandem":{"sha":"e9801a11","branch":"master"}}

**Comment by jonathanolson** [comment]
Should be fixed in master.

@phet-steele, can you verify? Changes may affect any time the period timer starts/stops or becomes visible/invisible, so testing those parts (in the next RC or whenever) would be great.

**Comment by phet-steele** [comment]
@jonathanolson this looks great on master.
