### ISSUE TITLE
Quantify Lab screen's gravity slider

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#178]
The Lab screen's Gravity slider is quantified (unlike the other screens) but still shows "None" and "Lots" for the slider range. The labels should show the proper numeric values: "0" and "25".

@arouinfar, or should they say "0.00" and "25.00"? 

<img width="278" alt="screen shot 2017-08-16 at 10 17 31 am" src="https://user-images.githubusercontent.com/5863899/29373651-298a1852-826c-11e7-9cc6-84fad2e59e2b.png">

For phetsims/QA/issues/34.

**Comment by arouinfar** [comment]
Thanks @phet-steele! I would prefer "0" and "25".

**Comment by jonathanolson** [comment]
Applied change, let me know if it looks good.

**Comment by arouinfar** [comment]
Looks great! Thanks @jonathanolson.
