### ISSUE TITLE
Slider pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#179]
@jonathanolson as discussed in today's design meeting, here's a mockup of the sliders in the style of Projectile Motion.
 
![image](https://user-images.githubusercontent.com/8419308/29438087-b6d6c2f4-8371-11e7-9838-dbb1117ddb2a.png)

Here are the changes overlayed on dev.14
![image](https://user-images.githubusercontent.com/8419308/29438178-34d62faa-8372-11e7-94f9-a913271fbcde.png)

Please let me know if you have any questions!

**Comment by arouinfar** [comment]
Just as a heads up -- @jonathanolson I tried my best to match the Projectile Motion style, but things in my mockups may be slightly off. If you run into anything fishy, do what you think is best, and don't worry about matching the mockups exactly.

**Comment by jonathanolson** [comment]
Implemented for length/mass.

I don't see a mock-up for how Gravity would look for the first two screens. Should it just have no readout, and the different labels?

**Comment by arouinfar** [comment]
Oops, sorry about that @jonathanolson! For the first two screens, omit the gravity readout and change the labels to "None" and "Lots". Would you like me to mock it up?

**Comment by jonathanolson** [comment]
No need, I understand.

**Comment by arouinfar** [comment]
Took a look at master, and the updated sliders are looking good. We may want to bump up the max/min labels up a px or two, though. They're a little on the small side.

**Comment by jonathanolson** [comment]
Bumped up tick labels by 2, let me know if it looks better now.

**Comment by arouinfar** [comment]
Looking much better, thanks!!

**Comment by jonathanolson** [comment]
Implemented, let me know how it looks (also pull scenery-phet)

I placed the planet X "question" where the slider goes (as I couldn't see any better place), and the readout is suppressed (for gravity) when planet X is elected.

**Comment by arouinfar** [comment]
Looks really good @jonathanolson! The location of the Planet X question looks great, and I don't mind the combobox being below the gravity slider. The only thing that looks a bit off to me are the gravity tweakers on the first two screens. Seems a bit odd/useless to have fine adjustment of an ill-defined parameter. 

@jonathanolson can we kill the gravity tweakers on Intro and Energy?

**Comment by jonathanolson** [comment]
Removed tweakers. Also adjusted the friction slider to use the same system for proper alignment, and cleaned up some code usage.

Let me know if it looks good (and if it's ready for RC).

**Comment by arouinfar** [comment]
Looks good! I think it's ready for RC, but maybe @kathy-phet would like to take a look at the latest changes first?

**Comment by kathy-phet** [comment]
@jonathanolson - This is looking very nice, thanks! One tweak request -- the font size for the readout value looks smaller than on projectile motion. Can you look at the difference and try to match them?  I'm not worried about the tickmark values being a smaller font, but I would like the readout of the actual value to be similar to projectile motion font size. This may mean that the slider spacing between the bottom of one slider control and the label row of the next slider control needs to be tweaked a few pixels to ensure that there is adequate negative space there. 

![image](https://user-images.githubusercontent.com/5096804/29719484-763302f0-8973-11e7-831b-2bc491159601.png)
![image](https://user-images.githubusercontent.com/5096804/29719490-7ed1f61e-8973-11e7-87eb-11a6dac492f5.png)

**Comment by jonathanolson** [comment]
Increased readout font size to match. Spacing should have adjusted itself automatically.

Let me know if that looks good, or if any further changes would be helpful.

Somewhat related, the gray stroke around the readouts kind of blends in against the gray background, and could be slightly darkened. Thoughts?

**Comment by kathy-phet** [comment]
I think the stroke is fine as is. 

But can you also increase the font readout for gravity on the lab screen?

**Comment by jonathanolson** [comment]
Changed (it looks like the readout was going past the maximum width set for i18n purposes). I've allocated more room for the readouts (so the gravity readout fits without being sized down).

**Comment by kathy-phet** [comment]
looks great. closing
