### ISSUE TITLE
General performance issues

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/pendulum-lab#18]
Our student tester reports:

There are performance issues on all three basic platforms however (Max OSX safarai, Windows Chrome, and iPad). Both OSX and Windows run fairly well but there is a noticeable stutter upon opening the simulation. The iPad runs slower than both OSX and Windows and also contains the same stutter as the other two. Besides the performance issue I would say this sim is looking great.

**Comment by andrey-zelenkov** [comment]
We made performance optimization at the stage of internal testing (redraw elements only when it's visible, prevent extra model updates). Please сheck the code and if there are any issues or lack about performance improvement let us know. We'll work on it. Thanks in advance!

**Comment by jonathanolson** [comment]
Noticed a good amount of low-hanging fruit to optimize, mostly related to the period trace shape (and other shapes like arrows).

**Comment by jonathanolson** [comment]
iPad 3 testing shows 25 FPS with just pendulum moving, 20 FPS with period trace on, 20 FPS with energy graph visible, 18 FPS with both visible. The works (velocity/acceleration arrows, energy graph, ruler, stopwatch running, period timer active showing a period trace, and 2 pendulums) is running at 11 FPS.

@ariel-phet, do you mind testing to see if performance is acceptable? It will be harder to squeeze out much more, but still possible.

**Comment by ariel-phet** [comment]
@arouinfar assigning to you to check out performance on iPad - see what you think in something like the lab scenario with both pendula and all options checked

**Comment by arouinfar** [comment]
iPad 2 performance is pretty good. I had the both pendulums going on the Lab screen with the vectors turned on and energy graph open, and everything looked smooth. The frame rate was pretty consistently 20 fps, except when the period timer was used (~13fps). Despite the low frame rates, the sim didn't seem laggy at all. The only noticeable issue was that the time displayed on the period timer seemed to be a passing a bit slowly compared to other platforms, but that was still pretty minor.

I'll take a look at the iPad 3 and report back.

**Comment by arouinfar** [comment]
Testing on an iPad 3 had similar results. The sim performs pretty well unless "the works" is running as @jonathanolson described. In that case, there's some lag, but I think it's acceptable given the hardware constraints of the iPad 3. I'll go ahead and close this issue.
