### ISSUE TITLE
Energy Graph Pixel Polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#180]
As discussed in today's design meeting:

- [x] Increase font size of labels
- [x] Increase width of bars
- [x] Add thin black stroke to the bars
- [x] Add off-scale arrow similar to Capacitor Lab: Basics
![screen shot 2017-08-17 at 3 51 30 pm](https://user-images.githubusercontent.com/8419308/29438234-91d1737c-8372-11e7-9cc6-3c54c85cbfaa.png)

**Comment by jonathanolson** [comment]
As I'm implementing this, I was wondering if the "total" bar arrow should potentially be able to display multiple colors (for the multiple types of energy that overflowed), or if it should just be one color.

If (for instance) the total overflows (in the image below) and just has a red arrow, students may think the total doesn't include kinetic/potential?:
![pendulum-lab-energy-1](https://user-images.githubusercontent.com/480878/29674249-d78cc15a-88ae-11e7-9a91-3683b7c5b234.PNG)

**Comment by arouinfar** [comment]
Great question @jonathanolson. I like the idea of a multi-colored arrow, but I think it could be a bit complicated/hard to interpret. Perhaps we could instead use a black arrow for the total, rather than matching the bar color. How does that sound?

**Comment by jonathanolson** [comment]
Sounds great to me (presumably only on the total).

**Comment by arouinfar** [comment]
Correct. The off-scale arrow for KE, PE, and thermal energy should match the color of the bar.

**Comment by jonathanolson** [comment]
Should be done now. Tried black, but wanted to test out gray (seems to match other colors better) to see how you like it:

![pendulum-lab-arrows](https://user-images.githubusercontent.com/480878/29676988-e8b9e752-88b6-11e7-932a-b256a5890d0b.PNG)
![pendulum-lab-arrows2](https://user-images.githubusercontent.com/480878/29676997-ec39f0f2-88b6-11e7-8286-af6cce0663cc.PNG)

Let me know if it looks good, and/or if the arrow color should change to black (or a different color).

**Comment by arouinfar** [comment]
The Energy Graph looks amazing @jonathanolson! Good call on the gray, I think it looks better. Looks like you've finished off the pixel polishing, so closing.
