### ISSUE TITLE
Question about "step function" size

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/pendulum-lab#182]
I was wondering whether there had been design discussion around the step function size in Pendulum lab? I was playing with it just now, and it seemed to be pretty course to me - making big steps. And the step size was the same on both the slow motion and the fast motion scales. The result was that you really could not get fine step control for showing very explicit observations ... like that at the peak of the motion is when velocity is zero, or that acceleration points up the string at the base of the swing. You can use slow-mo to show those things, but it is hard to show it passing through it with step. 

@jonathanolson - How is the step function done in the code? Is it something that is relatively easy to tweak, or is it hard to tweak?

**Comment by jonathanolson** [comment]
> How is the step function done in the code? Is it something that is relatively easy to tweak, or is it hard to tweak?

Very easy to tweak, and any values should work. Let me know if it should be different when in slow motion.

Currently it is stepping by 50ms (0.05s) of "true time" in all cases, even slow motion.

**Comment by kathy-phet** [comment]
Hi JO, 
Thanks. 
Can we try 10 ms of "true time" in all cases and see what that looks like?

**Comment by jonathanolson** [comment]
Changed, can you see how that feels?

**Comment by kathy-phet** [comment]
Feels great! Thanks. Also checked with Mike D and he says for his teaching this is good change.

**Comment by kathy-phet** [comment]
Closing.

**Comment by phet-steele** [comment]
Let's get @arouinfar's opinion on this before closing, although I'm sure this change is relatively harmless.

**Comment by kathy-phet** [comment]
Yep - Amy, what do you think?

**Comment by arouinfar** [comment]
@kathy-phet this was a great suggestion! I tested the new step size on master and everything looks good @jonathanolson. Closing.
