### ISSUE TITLE
A bit more negative space in Length/Mass panel

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/pendulum-lab#185]
@jonathanolson @kathy-phet @arouinfar 

To my eye, the Length/Mass panel looks a bit cramped and could use a bit of "breathing room" both between the Length and Mass and adjustments and between the two groupings of Mass/Length 1 and Mass length 2. In particular the sliders feel very vertically close to the readouts. 

For comparison

Here is the sim now

![pl](https://user-images.githubusercontent.com/4051174/29806431-6e533d76-8c4c-11e7-961d-afc0a4c8c8f4.PNG)

And here are some slight adjustments to negative space

![pl2](https://user-images.githubusercontent.com/4051174/29806377-325f8f22-8c4c-11e7-8b21-4ded9f7fee0e.png)

It seems we have the room? Was there a reason to make these so tight?

**Comment by ariel-phet** [comment]
Additionally I would consider bumping up the slider thumb/track vertical size slightly. These seem awfully small. The work just fine on iPad, but just seem a bit tiny compared to our norm for sliders. Perhaps a pixel or two larger? Am I missing some vertical space concern?

**Comment by ariel-phet** [comment]
https://github.com/phetsims/QA/issues/45

**Comment by arouinfar** [comment]
> Am I missing some vertical space concern?

No, not currently @ariel-phet. Quite some time ago, the panels on the Lab screen crowded the resetAllButton so much that the button was reduced to 75% of its normal size. Seems like we overcorrected a bit. I think your 2nd mockup showing the increased vertical spacing looks much better. Thanks!

> Additionally I would consider bumping up the slider thumb/track vertical size slightly.

We've increased the size of the slider thumb a bit, but it still looks a bit smaller than normal. In general, the sliders were modeled after Projectile Motion, which has small tick marks at the min/max. Not sure if the tick size matches Projectile Motion, though. 

@jonathanolson please
- [ ] Increase the vertical spacing to match @ariel-phet's 2nd mockup in https://github.com/phetsims/pendulum-lab/issues/185#issue-253536738
- [ ] Increase size of slider thumbs to match Projectile Motion
- [ ] Increase size of min/max tick marks on length/mass sliders to match Projectile Motion

**Comment by arouinfar** [comment]
@kathy-phet and I reviewed this issue together, so unassigning her too.

**Comment by jonathanolson** [comment]
> Increase the vertical spacing to match @ariel-phet's 2nd mockup in #185 (comment)
> Increase size of slider thumbs to match Projectile Motion

Done, let me know how it looks.

> Increase size of min/max tick marks on length/mass sliders to match Projectile Motion

Tick sizes are identical (5 view units tall).

**Comment by ariel-phet** [comment]
@jonathanolson version on Master looks good to me, thanks for the quick changes. Closing
