### ISSUE TITLE
Pointer areas - energy graph

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#186]
The zoom buttons have overlapping pointer areas:

<img width="186" alt="screen shot 2017-08-31 at 12 40 27 pm" src="https://user-images.githubusercontent.com/5863899/29939611-b13c00d8-8e49-11e7-867f-07af9d13a4f8.png">

Seen on macOs 10.12.6 Chrome. For phetsims/QA/issues/45.

**Comment by jonathanolson** [comment]
Fixed (and on 1.0 branch).

**Comment by phet-steele** [comment]
👍
