### ISSUE TITLE
[LoL Harness] Sim does not resize in window on IE11

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/pendulum-lab#189]
For phetsims/QA#45
Test device: Schrodinger, Bates & my personal Win 7 laptop

Operating System: Windows 7 & 8 64-bit

Browser: Internet Explorer 11

Problem description: Using IE, when testing in the LoL harness, the sim is too large in the window, and you can't see anything below the ruler checkbox. I wasn't even able to click report a problem from the PhET menu at the bottom of the screen, no matter how I moved the window and tried to resize (so the troubleshooting info is copied from a normal tab that's not LoL, I don't know if that makes any of the information inaccurate). The sim is too large when the window is full screen, and it also does not resize with the window at all if you make the window smaller. 
The screenshot below is what you can see with the window at the largest it can be.

![pendulumlab](https://user-images.githubusercontent.com/11947677/30125991-ac0a67dc-92f7-11e7-9fc8-b0bbb47a67ba.PNG)

[EDIT] Actually, I realized you can make the window become fullscreen by pressing F11, but the menu bar at the bottom is still not present. It no longer cuts off the stopwatch checkbox, or the buttons at the bottom of the sim though. 
![pendulumlab2](https://user-images.githubusercontent.com/11947677/30126195-7074ddb4-92f8-11e7-8694-669bb9176f5d.PNG)

Troubleshooting information (do not edit):
  
Name: ‪Pendulum Lab‬

URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-rc.2/pendulum-lab_en.html?legendsOfLearning

Version: 1.0.0-rc.2 2017-08-29 22:07:39 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; CMNTDFJS; .NET4.0E; .NET4.0C; rv:11.0) like Gecko

Language: en-US

Window: 1118x665

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"24c942a4","branch":"HEAD"},"babel":{"sha":"7619e2ca","branch":"master"},"brand":{"sha":"cfca902d","branch":"HEAD"},"chipper":{"sha":"c6ebc753","branch":"HEAD"},"dot":{"sha":"db33a2c7","branch":"HEAD"},"joist":{"sha":"18d08df1","branch":"HEAD"},"kite":{"sha":"dc5c4382","branch":"HEAD"},"pendulum-lab":{"sha":"b250e2d2","branch":"HEAD"},"phet-core":{"sha":"6bfeef5c","branch":"HEAD"},"phetcommon":{"sha":"7ec5d299","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"d539ecd7","branch":"HEAD"},"scenery-phet":{"sha":"7b214b9d","branch":"HEAD"},"sherpa":{"sha":"8a5d6d7f","branch":"HEAD"},"sun":{"sha":"9820ea30","branch":"HEAD"},"tandem":{"sha":"37243b99","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
It looks like a wrapper problem. On Chrome, it applies a CSS transform to the iframe, but there is no CSS transform set on IE11 when it is too small.

@samreid, who should be responsible for this?

**Comment by samreid** [comment]
To clarify, is the problem with the LOL wrapper harness?

**Comment by samreid** [comment]
When launching http://harness.legendsoflearning.com/ with http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-rc.2/pendulum-lab_en.html?legendsOfLearning in Chrome, there is a transform scale applied (see the `iframe style =` declaration).

![image](https://user-images.githubusercontent.com/679486/30152063-221ae54c-936f-11e7-9ead-10773d221123.png)

However, in IE11 there is no scale element:
![image](https://user-images.githubusercontent.com/679486/30152150-730be384-936f-11e7-8f24-c3b2c338e101.png)

If I manually type in a scale using IE11 dev tools, the frame size updates properly:
![image](https://user-images.githubusercontent.com/679486/30152205-a810ee30-936f-11e7-8692-8d008d51e43a.png)

Hence it seems that something in LOL code is failing to set the `transform: scale` element on the iframe for IE11.  It is not too problematic that the test harness doesn't work for IE11, but it would be a significant problem if the LOL HTML wrapper pages (that embed the simulations) have the same flaw.  We should report this to LOL.

**Comment by kathy-phet** [comment]
@samreid - Agreed, can you report this to LOL? 

Since this is on LOL side, I think we should proceed with assumption they will fix this issue, and it should not delay Pendulum Lab publication or submission to LOL.

**Comment by samreid** [comment]
I emailed:

Shaun, Josh & Faye,

PhET's QA team noticed a problem when running the Test Harness on IE11.  It seems that on other browsers the iframe is scaled with a style "translate: scale(...)" but this style element is missing when running in IE11, which causes the sim iframe to not resize properly and not fit properly within the page.  If this is only a problem in the harness, we may be able to work around it during testing, but our team was concerned that similar code may be used to render the simulations for teachers and students and cause similar problems for them.

More context and details (including screenshots) are available in this GitHub issue comment: https://github.com/phetsims/pendulum-lab/issues/189#issuecomment-327720393

Best Regards,
Sam

**Comment by kathy-phet** [comment]
Heard back from Josh. They do not support IE11. Closing.
