### ISSUE TITLE
Create LoL Icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#190]
Since this sim is being tested in the LoL harness, we'll also need LoL icons.

**Comment by arouinfar** [comment]
I've mocked up some draft icons based on the screen icons used in the sim. I prefer the first option for Intro, as it's a bit more visually interesting, but I tried a more "zoomed in" look as well.  @kathy-phet can you review?

![lol-icon-pl_intro-1](https://user-images.githubusercontent.com/8419308/30179547-01a11998-93ca-11e7-840c-dbfe1792208b.png)
![lol-icon-pl_intro-2](https://user-images.githubusercontent.com/8419308/30179546-019f9014-93ca-11e7-9528-dcbd83acadb2.png)
![lol-icon-pl_energy](https://user-images.githubusercontent.com/8419308/30179548-026ec8f2-93ca-11e7-94cd-e84e456f714c.png)
![lol-icon-pl_lab](https://user-images.githubusercontent.com/8419308/30179549-03432160-93ca-11e7-93cb-d923ff22831f.png)

**Comment by arouinfar** [comment]
After some feedback from @amanda-phet I've tweaked Energy icon. She had also expressed her preference for the 1st Intro icon in https://github.com/phetsims/pendulum-lab/issues/190#issuecomment-327890121. Here's the latest iteration @kathy-phet.

![lol-icon-pl_intro-1](https://user-images.githubusercontent.com/8419308/30182614-b0dcff4e-93d4-11e7-9177-935ee46b6ca4.png)
![lol-icon-pl_energy-2](https://user-images.githubusercontent.com/8419308/30182607-a7010ede-93d4-11e7-9e2b-f50ee1e86073.png)
![lol-icon-pl_lab](https://user-images.githubusercontent.com/8419308/30182610-ab0a0e04-93d4-11e7-9ffb-80633fe1f0ac.png)

**Comment by amanda-phet** [comment]
I definitely like the concept in the Energy icon! Not sure about the angle of the mass but I like seeing more of the graph.

**Comment by arouinfar** [comment]
Thanks @amanda-phet! Cleaned up the Energy icon a bit, and decided to go with a red pendulum. Replaced the image in my https://github.com/phetsims/pendulum-lab/issues/190#issuecomment-327912521 above.

**Comment by arouinfar** [comment]
Reviewed the icons with @kathy-phet and uploaded them to Drive.
