### ISSUE TITLE
Create custom version for UBC study

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#193]
@kathy-phet and I have been in contact with a researcher at the University of British Columbia who has requested a pared down version of Pendulum Lab for an study planned for January (with the sim delivered by December). Broadly, the researcher's goal is to compare a very specific lab done at UBC to the sim. The customization will involve removing most features from the sim and hardcoding some values (detailed below).

Mockup from UBC:
![image](https://user-images.githubusercontent.com/8419308/30505711-b0caa99c-9a33-11e7-8758-b1a3a5f1aec3.png)

Hardcode the following options, and hide the controls form the students
* Intro Screen only
* Length 1 = 0.83 m
* Mass 1 = 0.50 kg
* Gravity = Earth 
* Friction = 2                     
* Playback speed = Normal 
* Stopwatch always on  (hide checkbox)      

Completely disable/hide
* Energy & Lab screens
* Period Trace 
* Ruler                   
* Pendulum 2       
* Play/pause/next frame

I'm not sure what the next steps are for Pendulum Lab in terms of outfitting and whatnot. It may be good to create this version before master deviates from the published version, in case something pops up (not sure what).

@jonathanolson can you provide a time estimate to create the pared down Pendulum Lab? 

Assigning @ariel-phet too so he's in the loop. (Feel free to unassign yourself.)

**Comment by jonathanolson** [comment]
If it's just creating a branch and doing those changes, it should be quite quick. Maybe an hour at most?

I assume it would have no instrumentation for phet-io, correct?

**Comment by arouinfar** [comment]
Thanks @jonathanolson. No instrumentation is needed for the UBC study. 

@kathy-phet should @jonathanolson go ahead and proceed with creating the branch when time allows?

**Comment by ariel-phet** [comment]
@arouinfar - I am a little leery of pairing down the sim to that level. Can we know a bit more about the research goals? If they have anything to do with the "effectiveness" of simulations we most definitely DO NOT want to provide such a sim with a PhET branding. I think we need to be a little careful with the form in which we provide such a limited environment.

**Comment by kathy-phet** [comment]
The research goals were not about sim vs non sim in terms of pedagogy. It was more about in terms of can this lab activity be done remotely online or not. 

He wants it so pared down because its about measurement uncertainty and that is the focus of the data collection they do in lab and in the sim.

**Comment by kathy-phet** [comment]
We can also publish with the adapted logo too, if you are concerned about it.

**Comment by ariel-phet** [comment]
@kathy-phet yes definitely with the adapted logo

**Comment by jonathanolson** [comment]
Does http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.1.0-dev.1/pendulum-lab_en.html work nicely?

**Comment by arouinfar** [comment]
Looks good feature-wise @jonathanolson! I think the pendulum still has default mass and length, rather than values listed in https://github.com/phetsims/pendulum-lab/issues/193#issue-258184730. Can you double check that that these are the settings:
> Length 1 = 0.83 m
Mass 1 = 0.50 kg
Gravity = Earth
Friction = 2

**Comment by jonathanolson** [comment]
Sorry about that, will have it fixed.

**Comment by jonathanolson** [comment]
See http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.1.0-dev.2/pendulum-lab_en.html, it should have the desired attributes above. Sorry!

**Comment by arouinfar** [comment]
Looks good @jonathanolson! I'll send the link to UBC to review.

**Comment by arouinfar** [comment]
I sent the link to UBC a week ago and haven't gotten a response. I suppose that no news is good news, so I'll go ahead and close this issue. We can re-open at a later date, if necessary.
