### ISSUE TITLE
"Snap" to discrete angles

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/pendulum-lab#195]
The sim currently allows users to drag two masses to different angles, but the sim displays the same angle. For example, both of these pendulums were dragged to "40°"
![screen shot 2017-09-25 at 2 29 19 pm](https://user-images.githubusercontent.com/5090275/30829457-0a339dc8-a1fe-11e7-9168-82fb41a54986.png)

The [Flash version](https://phet.colorado.edu/sims/pendulum-lab/pendulum-lab_en.html) forced the pendulum to "snap" to discrete angles. Which we should try to emulate this behavior since the current implementation can be misleading. 

This was brought up by a teacher who was getting different period times for identically configured pendulums.

Assigning to @arouinfar for now.

**Comment by arouinfar** [comment]
This appears to be an oversight, as I thought the displacement already snapped to a whole number of degrees. @jonathanolson can you make this change? Once the angle is snappy, we can test again and see how well the period agrees.

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by arouinfar** [comment]
Looking good @jonathanolson!

**Comment by oliver-phet** [comment]
This looks good to me, too!

**Comment by jonathanolson** [comment]
Applied to the 1.0 branch, closing.

**Comment by phet-steele** [comment]
- Reopening so @oliver-phet can eventually email the user.

- As a consequence, you can now snap exactly to 180 degrees. This is causing a big problem where period times are wildly different:

![pl04](https://user-images.githubusercontent.com/5863899/32392232-687d409a-c09a-11e7-9974-6c3f2bde3f99.gif)


Don't ask how in the world the pendulum started swinging, it just did... and no I did NOT have friction during this. These problems are also closely reminiscent #91 and #128. @arouinfar @jonathanolson we should probably not allow snapping to 180 degrees, or if we do there needs to be more discussion.

**Comment by arouinfar** [comment]
> we should probably not allow snapping to 180 degrees

That would be perfectly fine with me @phet-steele @jonathanolson.

**Comment by jonathanolson** [comment]
Applied fix to master and the release branch. @phet-steele and @arouinfar can you verify?

**Comment by arouinfar** [comment]
I like the new behavior @jonathanolson, let's hope @phet-steele isn't able to break it. :)

**Comment by arouinfar** [comment]
@oliver-phet  can you please notify the user that we've published a maintenance release that addresses this issue?

**Comment by jonathanolson** [comment]
Looks like change using Util.sign worked on master, but had an older copy of dot in its SHAs. @phet-steele, https://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.2-rc.1/pendulum-lab_en.html should presumably solve the issue on production?

**Comment by phet-steele** [comment]
Good to go JO, thanks for the quick turn around.

**Comment by jonathanolson** [comment]
Deployed, http://phet.colorado.edu/sims/html/pendulum-lab/1.0.2/pendulum-lab_en.html should have fix in place.

**Comment by oliver-phet** [comment]
Email to user sent. Closing for now.
