### ISSUE TITLE
Clear thermal energy on drag of pendulum mass

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/pendulum-lab#196]
After discussing the UX in Masses in Springs, it seemed like we should revisit pendulum lab so that when the user grabs a mass, the thermal energy is automatically cleared, since in essence the user is starting a new experiment.

**Comment by jonathanolson** [comment]
Implemented, can you confirm?

**Comment by arouinfar** [comment]
Things were looking pretty good until I tested the `ClearThermalButton`. In master, the button is behaving like the stop button (pendulum stops moving and all energy is cleared).

**Comment by jonathanolson** [comment]
Investigating (doesn't look related to my last 2 patches, but also isn't happening on the live version).

**Comment by jonathanolson** [comment]
Looks like a common-code change may have broken this.

**Comment by jonathanolson** [comment]
Found the bug in DynamicProperty (I fairly recently introduced it.

Should be working nicely in master now, sorry!

**Comment by jonathanolson** [comment]
Will need to pull common code on phettest.

**Comment by arouinfar** [comment]
Looking good @jonathanolson! `ClearThermalButton` is behaving as expected now.

**Comment by jonathanolson** [comment]
Applied to 1.0 branch, closing.

**Comment by phet-steele** [comment]
Good in 1.0.1-rc.1.
