### ISSUE TITLE
Planned 1.0.1 maintenance release

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#197]
Planning to handle before pushing this out:

- https://github.com/phetsims/pendulum-lab/issues/196
- https://github.com/phetsims/pendulum-lab/issues/195
- https://github.com/phetsims/joist/issues/447
- phetsims/joist#449 (EDIT: added this issue after dev meeting discussion)

**Comment by jonathanolson** [comment]
Also will include:

- https://github.com/phetsims/pendulum-lab/issues/198

**Comment by samreid** [comment]
Please see also https://github.com/phetsims/joist/issues/449#issuecomment-340263119, we are considering picking up some other commits for this maintenance release.

**Comment by jonathanolson** [comment]
I'm going to apply the commits for the issues I've mentioned above to the release branch.

@samreid, should I wait on https://github.com/phetsims/joist/issues/449#issuecomment-340263119 before creating the RC for testing?

**Comment by jonathanolson** [comment]
Applied patches to the release branch (and tested to verify) for the 4 issues I linked above.

Will wait to hear about the joist screen issue to see if it should be included in the release.

**Comment by samreid** [comment]
> @samreid, should I wait on phetsims/joist#449 (comment) before creating the RC for testing?

Yes, that would be great.  We are waiting on @kathy-phet recommendation.

**Comment by kathy-phet** [comment]
What does Ariel think here? I can go either way, if we won’t run into some other complication in tracking stats or something connected.
Kathy

Sent from my iPhone

On Nov 2, 2017, at 10:34 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


@samreid<https://github.com/samreid>, should I wait on phetsims/joist#449<https://github.com/phetsims/joist/issues/449> (comment) before creating the RC for testing?

Yes, that would be great. We are waiting on @kathy-phet<https://github.com/kathy-phet> recommendation.

**Comment by samreid** [comment]
Marked for developer meeting to ask @ariel-phet and make sure everyone is in the loop on this change.

**Comment by jonathanolson** [comment]
Also need to look into a good fix for https://github.com/phetsims/joist/issues/447, since the latest fix may revert https://github.com/phetsims/pendulum-lab/issues/187

**Comment by pixelzoom** [comment]
11/2/2017 dev meeting:
We discussed phetsims/joist#449, see notes there.
phetsims/joist#449 will be part of this maintenance release, added to list in https://github.com/phetsims/pendulum-lab/issues/197#issue-266911539.

**Comment by jonathanolson** [comment]
Have an RC version with all of the fixes: https://github.com/phetsims/QA/issues/62

**Comment by jonathanolson** [comment]
Deployed 1.0.1, closing.
