### ISSUE TITLE
Reverse gradient on masses

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#198]
While reviewing Masses and Springs, I noticed that the gradient on the masses was reversed (highlight should be on the left). Looks like the behavior was copied from Pendulum Lab which is also reversed. We assume the light source is in the upper left, so the highlights should be on the left side of the masses, not right.

@jonathanolson can you reverse the gradient on the masses and include it in the upcoming maintenance release #197?

**Comment by jonathanolson** [comment]
I also applied a "fix" to the pendulum icons (for deciding 1 or 2 pendula). It was actually sort of broken so the gradient wasn't applied correctly, so I applied a "reversed" fixed version that has "less" highlight than the actual masses.

Does this look good?

**Comment by arouinfar** [comment]
Looks good @jonathanolson! We'll also need to update the Intro and Lab screen icons. I've emailed updated assets to you.

**Comment by jonathanolson** [comment]
Copied in, but sim is failing on laugh with "homeScreenIcon is too small: 544". The old size was 694x472, new size is 544x374.

**Comment by arouinfar** [comment]
@jonathanolson here are the updated .png at the correct resolution. Do the navbar icons also need to be re-exported?

[intro-screen-icon.png](https://user-images.githubusercontent.com/8419308/32298526-2050cde2-bf18-11e7-9d51-1113245abc49.png)
[lab-screen-icon.png](https://user-images.githubusercontent.com/8419308/32298527-20781726-bf18-11e7-9c57-f04027b26946.png)

**Comment by jonathanolson** [comment]
Added, does everything look good for this issue?

**Comment by arouinfar** [comment]
Looks great! Thanks @jonathanolson.

**Comment by arouinfar** [comment]
Since this is part of #197, I'll leave this open and marked as fixed-pending-testing.

**Comment by jonathanolson** [comment]
Applied to the 1.0 branch, closing (will note all issues to verify in qa issue)
