### ISSUE TITLE
Period trace should fade away on Lab screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#20]
After tracing the pendulum's period, the line should gradually fade away. On the Lab screen, the trace disappears immediately instead of fading out.

Example of proper fading:
![screen shot 2015-01-12 at 12 41 00 pm](https://cloud.githubusercontent.com/assets/8419308/5709596/6aa2412e-9a58-11e4-9bc8-c47eb7cae2e8.png)

This fading works properly on the Intro and Energy screens, but not on the Lab screen.

**Comment by andrey-zelenkov** [comment]
Fixed period trace fading for lab screen. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
@ariel-phet, can you please verify this? I don't have the ability to check this without having a new dev version published.

**Comment by ariel-phet** [comment]
Looks good, closing
