### ISSUE TITLE
'grunt published-README' not run in 1.0 branch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/pendulum-lab#204]
The 1.0 branch of this sim still indicate that the sim is unpublished.

The master checklist for sims says:

> - [ ] README.md updated using `grunt published-README` (in master and release branch)

**Comment by pixelzoom** [comment]
This appears to be a problem with `grunt production`.  It runs `grunt published-README` in master, but not in the release branch.

**Comment by jonathanolson** [comment]
I was not aware that this needs to be run in both branches (or that anyone would check the README in a branch). Is this something we should do? (tagging for dev meeting).

**Comment by pixelzoom** [comment]
Why would you want the README to be bogus, even in a non-master branch?

**Comment by jonathanolson** [comment]
Untagging, will figure out a way to patch it in both places.

**Comment by pixelzoom** [comment]
Looks like this was done at some point, though there's no commit associated with this issue.  Closing.
