### ISSUE TITLE
replace PeriodTimerNode with SCENERY_PHET/TimerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/pendulum-lab#207]
Replace PeriodTimerNode with SCENERY_PHET/TimerNode.

**Comment by jonathanolson** [comment]
Just to confirm, are you saying that TimerNode has been generalized so it can support PeriodTimerNode, which has the appearance:

![pendulum-lab-period-timer](https://user-images.githubusercontent.com/480878/49125809-a30adf80-f27e-11e8-979e-288960fe775f.png)

whereas I believe TimerNode has this appearance:

![timer-node](https://user-images.githubusercontent.com/480878/49125867-c9c91600-f27e-11e8-9f9c-cd63362d06cb.png)
