### ISSUE TITLE
Cannot switch from Planet X to Custom gravity

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#22]
It is currently impossible to switch from Planet X to Custom gravity. When using the drop-down menu to switch from an option with a known value of gravity to Custom, the slider maintains its current position/value. However, when switching from Planet X to Custom, the value of g should return to whatever value it had immediately before Planet X was selected. 

The desired behavior is best exemplified in the Bending Light Java sim, so using it as an example here.
(http://phet.colorado.edu/en/simulation/bending-light) 

Setting a custom value:
![image](https://cloud.githubusercontent.com/assets/8419308/5908985/7c44810a-a569-11e4-9960-4b91a941321a.png)
Using the drop-down menu to select an option with an unknown value:
![image](https://cloud.githubusercontent.com/assets/8419308/5908987/83904994-a569-11e4-9490-e7052315a49a.png)
Using the drop-down menu to return to the custom option:
![image](https://cloud.githubusercontent.com/assets/8419308/5909075/59bc9f2c-a56a-11e4-9b33-0d7125cdb952.png)

Another example:
Selecting water from the drop-down menu:
![image](https://cloud.githubusercontent.com/assets/8419308/5909023/f5db7aaa-a569-11e4-8b42-fd2600ce643b.png)
Choosing an option with an unknown value:
![image](https://cloud.githubusercontent.com/assets/8419308/5909025/fc8b4bbe-a569-11e4-95c8-d70a21f5c5fc.png)
Selecting custom:
![image](https://cloud.githubusercontent.com/assets/8419308/5909037/12905706-a56a-11e4-8c03-8f986411aabb.png)

Assigning to @andrey-zelenkov

**Comment by andrey-zelenkov** [comment]
Fixed switching from Planet X to Custom Planet. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Looks good! Closing.
