### ISSUE TITLE
Inconsistent layering

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#23]
The period trace currently draws on top of the menus on the left and goes behind the menu on the right. The mass is always behind the menus. It would be best if the masses were always visible above the menus.

![screen shot 2015-01-26 at 3 11 13 pm](https://cloud.githubusercontent.com/assets/8419308/5909795/0f4ae352-a571-11e4-9aa5-a826cd47b3ca.png)

The tools are not consistently layered. The period timer and stopwatch are above the menus/masses, but the ruler is behind. Move the ruler up, so it is layered above the menus/masses like the other tools.
![image](https://cloud.githubusercontent.com/assets/8419308/5909806/27074846-a571-11e4-9bc7-b102cf8da3eb.png)

**Comment by andrey-zelenkov** [comment]
Layering was moved from the original sim (in the original simulation ruler was beneath the other nodes). Please let us know if there are more differences. Ruler and pendulum nodes moved up, reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Thanks for adjusting the layering. Can you move the period trace up so that it appears on top of the menus with the pendulum? It looks a bit strange for the pendulum to be in front of a menu while the trace is behind. 

![image](https://cloud.githubusercontent.com/assets/8419308/5968178/ffd19714-a7d1-11e4-85dd-7fc3c3f61553.png)

Everything else looks good. Reassigning to @andrey-zelenkov.

**Comment by andrey-zelenkov** [comment]
Move period trace node up to pendulum node. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Great, thanks! Closing.
