### ISSUE TITLE
Period Timer should be able to immediately re-record period

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#24]
Currently, the period timer will not re-record the pendulum's period until after the period trace has completely faded away.

<b>To reproduce:</b>
1) While pendulum 1 is swinging, start the period timer.
2) After period finishes recording, immediately press on the play/record button to start again.  The play/record will turn into the reset button, but the period will not be recorded:
![image](https://cloud.githubusercontent.com/assets/8419308/5909993/defbd2b8-a572-11e4-95c7-5e5edeb74f0c.png)

<b>Desired behavior:</b>
If the play/record button is pressed immediately after the period timer finishes recording, the now-fading period trace should immediately disappear (instead of continuing to fade) and the timer should start recording/tracing the new period. There shouldn't be a required "cooling down" period in which the timer is inoperable.

**Comment by andrey-zelenkov** [comment]
Added immediate re-record of period for Period Timer. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Fixed, closing.

**Comment by arouinfar** [comment]
When trying to verify #77, I found this issue (as described in the original post) to be present in the latest pull from gitdev. Reopening and assigning to @andrey-zelenkov.

**Comment by arouinfar** [comment]
Issue reopened in error (remote pull of git-dev is not working), so closing.
