### ISSUE TITLE
Possible to record period while pendulum is not in motion

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#25]
It is possible to record the period of the pendula while they are not in motion. This only appears to be an issue after their motion has been stopped using friction.

<b>To reproduce:</b>
1) Open the lab screen, and displace both pendula.
2) Increase friction to the maximum value and wait for the pendula to stop swinging. The displacement tick marks will still be showing in the protractor, even though they have been stopped.
3) Start period timer. The period will be recorded even though the pendulum is not in motion.

Measuring the period of pendulum 1:
![image](https://cloud.githubusercontent.com/assets/8419308/5910869/311d12a6-a57c-11e4-8a50-eebe841d4e14.png)

Measuring the period of pendulum 2:
![image](https://cloud.githubusercontent.com/assets/8419308/5910865/29bb4834-a57c-11e4-8e23-636c8f0d2a58.png)

**Comment by andrey-zelenkov** [comment]
Prevented infinite motion after friction. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Fixed, closing.
