### ISSUE TITLE
Mock-up screenshots should not be included

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#26]
They are currently loaded into the sim in the main:
```js
  var screenshot1 = require( 'image!PENDULUM_LAB/pendulum-lab-screen-1.png' );
  var screenshot2 = require( 'image!PENDULUM_LAB/pendulum-lab-screen-2.png' );
  var screenshot3 = require( 'image!PENDULUM_LAB/pendulum-lab-screen-3.png' );
```
then passed to each screen and to PendulumLabView. They should not be in the simulation at all (as it increases the download size), and the code related to the mock-ups should be removed.

**Comment by andrey-zelenkov** [comment]
Removed mock-up screenshot images from simulation. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
