### ISSUE TITLE
Type documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#29]
Instead of
```js
// some comments (type: Vector2)
```
the PhET convention is to follow JSDoc with the type first, like:
```js
// {Vector2} some comments
```

Example is for location in Movable.js

**Comment by andrey-zelenkov** [comment]
Fixed type documentation for comments. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
