### ISSUE TITLE
PropertySet property access

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#30]
NOTE: not assigned yet, pending on https://github.com/phetsims/axon/issues/43

In general the following is preferred:
```js
this.locationProperty
```
to the following style:
```js
this.property( 'location' )
```
for readability and performance concerns.

Example: Movable.js

**Comment by andrey-zelenkov** [comment]
PropertySet property access changed. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
