### ISSUE TITLE
Height/velocity inconsistencies with Pendulum.js

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#31]
It seems pendulum.height is a property that always has the value 0, but pendulum.getHeight() returns the anticipated value. Same with velocity.

This should be fixed so that we don't have incorrect values (feel free to remove the unused properties from the pendulum).

**Comment by andrey-zelenkov** [comment]
Removed unused properties from the pendulum. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
