### ISSUE TITLE
Prefer usage of Vector2.setPolar

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#32]
Instead of the following:
```js
this.accelerationVector.setXY( -accelerationMagnitude * Math.cos( accelerationAngle ), -accelerationMagnitude * Math.sin( accelerationAngle ) );
```
It's much simpler to call:
```js
this.accelerationVector.setPolar( -accelerationMagnitude, accelerationAngle );
```

**Comment by jonathanolson** [comment]
This usage is in Pendulum.js, but please check for others.

**Comment by andrey-zelenkov** [comment]
Simplify code by using Vector2.setPolar instead of Vector2.setXY. Thank you for advice! Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
