### ISSUE TITLE
PhET-style variable declarations

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#33]
Declarations of the form:
```js
var a = 5,
  b = 6,
  c = 7;
```
should be changed to
```js
var a = 5;
var b = 6;
var c = 7;
```
to match our coding guidelines. It helps to be able to quickly rearrange by swapping lines, delete lines, and add variables faster, and is a bit easier to read.

**Comment by jonathanolson** [comment]
An example of this is in updateAccelerationVector() in Pendulum.js, but please look for other cases.

**Comment by andrey-zelenkov** [comment]
Change variable declarations to PhET-style. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
