### ISSUE TITLE
Note that Pendulum.getPeriod() is only a small-angle approximation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#34]
Consider renaming it to getApproximatePeriod(), as it can be more than 5% off for displacements of 50 degrees.

**Comment by andrey-zelenkov** [comment]
Rename Pendulum.getPeriod method to more convenient Pendulum.getApproximatePeriod. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks.
