### ISSUE TITLE
Top-level file documentation fixes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#36]
PeriodTrace.js documentation states "Single pendulum model.", PeriodTraceNode says it's a "Protractor node", PendulumLabModel.js and EnergyModel.js have the same description, etc.

This should be fixed, and any other incorrect file documentation (I haven't exhaustively checked).

**Comment by andrey-zelenkov** [comment]
Top level file documentation fixes made. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks.
