### ISSUE TITLE
Type documentation in PeriodTrace

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#37]
Incorrect type:
```
* @param {Array} pendulumModel - Pendulum model.
```

Generally we document property types as:
```
* @param {Property<boolean>}
```
instead of just 
```
* @param {Property}
```

**Comment by andrey-zelenkov** [comment]
Type documentation fixes for parameters have made. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
