### ISSUE TITLE
Dropping the "Model" suffix for many variables/properties

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#38]
It's idiomatic for PhET sims to not use "pendulumModels", "planetModels", "rulerModel", "stopwatchModel", etc., and prefer "pendulums", "planets", "rulers" and "stopwatch".

This generally applies to any type which does not end in "Model" itself (please keep PendulumLabModel's name).

**Comment by andrey-zelenkov** [comment]
Dropped "Model" suffix for variables and properties. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
