### ISSUE TITLE
Reset handling

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#39]
Generally, calling prototype methods on non-self objects is highly discouraged. Instead of code like:
```js
PropertySet.prototype.reset.call( this.rulerModel );
```
we should have:
```js
this.rulerModel.reset();
```
and similar for all usages like that.

**Comment by andrey-zelenkov** [comment]
Reset handling changed (avoid calling prototype methods). Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
