### ISSUE TITLE
no doc directory

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/pendulum-lab#40]
Every sim is supposed to have a doc/ directory, containing model.txt (high-level model description) and implementation-notes.text (notes for developers).

**Comment by andrey-zelenkov** [comment]
Added doc/ directory and model.txt and implementation-notes.txt. Reassign to @pixelzoom for verification.

**Comment by pixelzoom** [comment]
I'm not familiar with this sim. So assigning to @jonathanolson to determine whether model.txt and implementation-notes.txt provide sufficient information.
