### ISSUE TITLE
PeriodTrace pendulum parameter

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#46]
Is the pendulum parameter to PeriodTrace ever something that isn't a Pendulum that extends PropertySet? Otherwise it should be typed {Pendulum}.

**Comment by andrey-zelenkov** [comment]
Fixed jsdoc description for pendulum parameter. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
