### ISSUE TITLE
PeriodTrace pendulum angle link computes with null

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#47]
Because link() is called on the angle property, oldAngle is null the first time it is triggered. Please lazyLink if that is desired, or explicitly handle the null case (instead of adding and multiplying with null).

**Comment by andrey-zelenkov** [comment]
Change link() to lazyLink() call for angleProperty. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
