### ISSUE TITLE
EMPTY_SHAPE potentially unnecessary?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#48]
EMPTY_SHAPE is set to new Shape() and only used for Paths. Using null would work just as well. Any reason EMPTY_SHAPE is used instead?

**Comment by andrey-zelenkov** [comment]
Remove unnecessary EMPTY_SHAPE. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
