### ISSUE TITLE
Pendulum.angle documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#49]
Since we are using sign-dependent code like the following:
```
newAngle * oldAngle < 0
```
where there is a significant difference between (pi * -pi) and (3pi * pi), even if the angles are the same mod 2pi.

Please document the acceptable range and where it is rounded.

**Comment by andrey-zelenkov** [comment]
Added Pendulum.angle documentation. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Could the documentation be added where Pendulum.angle is declared?

**Comment by andrey-zelenkov** [comment]
Move 'angle' property description comments to Pendulum.angle.

**Comment by jonathanolson** [comment]
Looks great, thanks!
