### ISSUE TITLE
PeriodTrace's anticlockwise flags

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#51]
It seems like PeriodTrace could be simplified with a single anticlockwise flag (for the intial movement). Every anticlockwise flag for [1], [2], and [3] are determined by [0]'s anticlockwise. Additionally, every access of anticlockwise in the node has a specific index specified, so the signs can be applied there.

Is there another reason anticlockwise is duplicated?

**Comment by andrey-zelenkov** [comment]
Remove unused 'anticlockwise' flags and simplify period trace model. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
