### ISSUE TITLE
PeriodTrace documentation for visibility

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#52]
Documentation on the difference between isPeriodTraceVisibleProperty (parameter) and isVisible (property) would be helpful for the future.

Also, isPeriodTraceVisibleProperty's comment is "Flag property to track pendulum path." Is that correct?

**Comment by andrey-zelenkov** [comment]
Added documentation for PeriodTrace 'isVisible' property, fixed documentation for isPeriodTraceVisibleProperty. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
