### ISSUE TITLE
String variables should start with a lowercase character

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#53]
For example:
```
var EarthString = require( 'string!PENDULUM_LAB/earth' );
```
should be changed to something like:
```
var earthString = require( 'string!PENDULUM_LAB/earth' );
```

Generally an upper-case first character is reserved for constants (all upper case) or types (we can't do "new EarthString()")

**Comment by andrey-zelenkov** [comment]
String variables names fixes (change first character to lowercase). Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
