### ISSUE TITLE
Purpose of extra Planets.js enumeration?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#54]
It seems cleaner to have this code within Planet.js:
```js
Planet.EARTH = new Planet( .... );
```
and there would be no need for Planets.js.

Additionally, it seems like comparisons are being done with strings for planet names. It seems much cleaner to only do comparisons with Planet objects themselves (e.g. GravitySliderWithListNode.js would have planetProperty be a Property.<Planet> instead).

Is there a reason why string literals are needed instead of comparing objects?

**Comment by andrey-zelenkov** [comment]
Remove Planets.js, refactor Planet.js. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
