### ISSUE TITLE
Document FrictionSliderNode.js padding

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#57]
It looks like padding is provided to the VBox, but only one node is added to the VBox. Can a comment be added to explain why this is done, or can it be done in a cleaner way?

See #56.

**Comment by andrey-zelenkov** [comment]
Removed extra VBox node for FrictionSliderNode. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
