### ISSUE TITLE
Add friction property to PendulumLabModel

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#58]
It seems cleaner to add a friction property to the base model that is always 0 for the first screen, than it is to add custom properties to other screen's models.

In addition, this can remove the cast in PendulumLabModel where ```this.friction || 0``` is used.

See #56.

**Comment by andrey-zelenkov** [comment]
friction property added to PendulumLabModel. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks great, thanks!
