### ISSUE TITLE
FrictionSliderNode reset

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/pendulum-lab#59]
It seems like the slider node should listen to the frictionSlider value, so that when the frictionProperty is reset(), the value on the slider node will change to the corresponding value.

Then, we don't have to have a reset() function on FrictionSliderNode, AND if there is another place where we modify friction (say through 3rd party tools), then the slider will properly update.

See #56.

**Comment by andrey-zelenkov** [comment]
Made refactoring for FrictionSliderNode reset function. Reassign to @jonathanolson for verification.

**Comment by jonathanolson** [comment]
Looks good, thanks!
