### ISSUE TITLE
Unfinished comment in PendulumLabRulerNode

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#62]
During code review #56, I noticed this code in PendulumLabRulerNode:

```js
    RulerNode.call( this, rulerWidth, 34, tickWidth, rulerTicks, rulerUnitsString, { // -1px to
```

It's not clear to me what "// -1px to" means. Is this an unfinished comment? Can you either remove it or clarify what it means?

Also, it might be nice to make a var rulerHeight = 34, so it's more clear what that constant is doing there in the call to RulerNode.

**Comment by pixelzoom** [comment]
> Also, it might be nice to make a var rulerHeight = 34, 

We might consider moving all of the constructor params to options. All of these parameters could have default values, and options are more "self documenting".

**Comment by andrey-zelenkov** [comment]
Remove outdated comment, move rulerHeight to constants block. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks good. Closing
