### ISSUE TITLE
Document Array types

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#64]
During code review #56, I noticed many JSDoc strings like the following:

```js
   * @param {Array} pendulums - Array of pendulum models.
```

The PhET convention elsewhere is to document the type of the items in the array, so something like 

```js
   * @param {Array.<Pendulum>} pendulums - Array of pendulum models.
```

**Comment by andrey-zelenkov** [comment]
Fixed documentation for Array types. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks good, closing
