### ISSUE TITLE
Should numbers be translatable?

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#65]
During code review #56, I noticed that numbers are cast to strings and put into TextNodes in a few places in this sim.

```js
          new Text( (pendulumIndex + 1).toString(), { font: FONT, fill: 'white', centerY: RECT_SIZE.height / 4, centerX: 0 } ),
```

I'm not sure that we need to translate these or not, but I want to at least make an issue that we can come back to when we get further along in the translation process.

Leaving unassigned for now.

**Comment by jonathanolson** [comment]
I could imagine translators wanting to have the equivalent of 'First Mass' / 'Primary Mass' / etc. instead of 'Mass 1', but I'll leave the translation decision up to design.

**Comment by arouinfar** [comment]
I think it's best to use the same convention as Hooke's Law, so the the Mass and Length strings would be remain the equivalent of "Mass 1" or "Length 2" like in the situation below.
![image](https://cloud.githubusercontent.com/assets/8419308/11126844/3e1ed07a-892e-11e5-96f5-931c58b663f4.png)
