### ISSUE TITLE
Acceleration Arrows in PendulumsNode

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#66]
During code review #56, I noticed this code:

```js
        options.isAccelerationVisibleProperty.linkAttribute( accelerationArrow, 'visible' );

        // add visibility observer
        options.isAccelerationVisibleProperty.link( function( isAccelerationVisible ) {
          accelerationArrow.visible = isAccelerationVisible;
          pendulum.updateAccelerationVector();
        } );
```

It looks to me like the call to link is totally unnecessary after linkAttribute has already been called. The call to pendulum.updateAccelerationVector() also looks unnecessary, and it seems like it is getting called every frame in any case.

Is this correct, or is there some reason for having this code that I am not seeing? Please either document why it needs to be here or remove.

Also, it might be nice to change the link call in the velocity vector code to linkAttribute as well to make the two consistent.

```js
        options.isVelocityVisibleProperty.link( function( isVelocityVisible ) {
          velocityArrow.visible = isVelocityVisible;
        } );
```

**Comment by andrey-zelenkov** [comment]
Replace 'link' to 'lazyLink' for accelerationVector, added comments, fixed bug for velocityVector. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks better, thanks for the comments. Closing
