### ISSUE TITLE
Nav icons are white rectangles

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#67]
Looks like we need icons for the screens on the nav-bar and home screen.

I assume this is a known issue, but since it isn't being tracked here I thought I would create an issue for it.

**Comment by arouinfar** [comment]
@aaronsamuel137, the home screen icons have been designed, but this was done after the spec went out. @ariel-phet who should I send the artwork to?

**Comment by ariel-phet** [comment]
@arouinfar, send them to @aaronsamuel137 

Since they were not in the spec, best for us to just take care of it ourselves

**Comment by arouinfar** [comment]
Artwork has been emailed to @aaronsamuel137 to implement.

**Comment by aaronsamuel137** [comment]
Assigning to @jonathanolson for review - I used the mipmap plugin so the icons would downscale better on firefox for the navbar.

**Comment by jonathanolson** [comment]
Looks good, I'll take care of sizing in https://github.com/phetsims/pendulum-lab/issues/107.
