### ISSUE TITLE
Node options should be passed to Node.call() when possible

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#68]
During code review #56 I noticed this code in PeriodTraceNode

```js
    Node.call( this, options );

    this.rotation = Math.PI / 2;
```

It seems like the usual PhET convention would be to pass rotation in as one of the Node options like so:

```js
    Node.call( this, _.extend( {
      rotation: Math.PI / 2
    }, options ) );
```

This way it is more clear that rotation is a Node a option and not a private attribute. Is there any reason why this isn't being done? Will you either change this or add some documentation. Thanks.

**Comment by aaronsamuel137** [comment]
A similar pattern occurs in PendulumLabView:

```js
    var returnButtonNode = new ReturnButtonNode( {
      listener: pendulumLabModel.returnHandler.bind( pendulumLabModel )
    } );
    returnButtonNode.centerX = resetAllButton.bounds.minX - 75;
    returnButtonNode.centerY = height - SCREEN_PADDING.BOTTOM - 5;
```

**Comment by aaronsamuel137** [comment]
And in StopwatchNode:

```js
    Timer.call( this, stopwatch.elapsedTimeProperty, stopwatch.isRunningProperty );

    this.centerX = toolsControlPanelNodeBounds.maxX - this.width / 2;
    this.centerY = toolsControlPanelNodeBounds.minY - this.height / 2 - 5;
```

**Comment by andrey-zelenkov** [comment]
Added using of Node.call in PeriodTraceNode and PendulumLabView. Center of StopwatchNode depend on Times's size and can be set only after creating of Timer. Reassign to @aaronsamuel137 for verification.

**Comment by pixelzoom** [comment]
@aaronsamuel137 Actually, the more common pattern is:

```js
function MyNode(..., options ) {

  options = _.extend( {
     // define options and their default values
  }, options );

  Node.call( this );

  // add children, do other things

  this.mutate( options );
}
```

If you pass options to `Node.call` before children are added, transformation-related options will cause an assertion error (something like "suspicious matrix operation") because the bounds of a Node are Bounds2.NOTHING by default.  Doing `this.mutate( options )` as the final step in the constructor ensures that the node's portion of the scene graph is defined before applying options.

**Comment by aaronsamuel137** [comment]
@pixelzoom, I'm aware of that pattern, but in these cases there was no need to call this.mutate( options ).

Would you suggest using that pattern everywhere for consistency even when it isn't necessary?

**Comment by pixelzoom** [comment]
No need to use that pattern everywhere. And I didn't look at the specific case that here. But the example you gave was for Node, and `Node.call( this, options )` is highly likely to cause an assertion failure. So for subtypes of Node, it's highly recommended to use the `this.mutate` pattern.

**Comment by aaronsamuel137** [comment]
OK thanks for pointing that out and clarifying.

**Comment by aaronsamuel137** [comment]
This looks good to me as far as these specific instances are concerned. Closing
