### ISSUE TITLE
JSDoc in SystemSlidersNode

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#70]
During code review #56 I noticed the JSDoc in SystemSlidersNode:

```js
   * @param {PendulumLabModel} pendulumLabModel - Model of Lab screen.
```

Is this correct? It seems like this component is used on all screens, not just the Lab screen.

**Comment by andrey-zelenkov** [comment]
Fixed JSDoc comment in SystemSlidersNode for 'pendulumLabModel' param. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks good. Closing
