### ISSUE TITLE
JSDoc for setLabelText

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#72]
During code review #56 I noticed that the function setLabelText of ToolsControlPanelNode has no JSDoc.

I think it would be helpful to have a little documentation describing where this function is used and why it is necessary.

**Comment by andrey-zelenkov** [comment]
Added JSDoc for setLabelText. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks good. Closing
