### ISSUE TITLE
Take a screenshot for 1.0!

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#73]
Noticed during code review #56. Not sure who should be assigned for this.

**Comment by aaronsamuel137** [comment]
Should be 2048x1344, PNG, 32-bit color.

**Comment by jonathanolson** [comment]
I'll take care of this once we're more finalized.

**Comment by phet-steele** [comment]
Will self-assign and put on hold until 1.0 is ready.

**Comment by phet-steele** [comment]
@arouinfar, please post what you would like this to be.

**Comment by arouinfar** [comment]
@phet-steele I'm thinking something like this for the screenshots, with either (1) or (3) being the main screenshot. What do you think?

1. <img width="915" alt="screen shot 2017-09-08 at 11 36 54 am" src="https://user-images.githubusercontent.com/8419308/30224044-6f9f332e-948a-11e7-925c-613af292b444.png">
2. <img width="916" alt="screen shot 2017-09-08 at 11 35 39 am" src="https://user-images.githubusercontent.com/8419308/30224043-6f9e57c4-948a-11e7-930e-08d0deb2b163.png">
3. <img width="915" alt="screen shot 2017-09-08 at 11 34 39 am" src="https://user-images.githubusercontent.com/8419308/30224041-6f9d7ed0-948a-11e7-94a8-3cdc57d6b831.png">
4. <img width="914" alt="screen shot 2017-09-08 at 11 43 57 am" src="https://user-images.githubusercontent.com/8419308/30224196-099103ae-948b-11e7-8ec8-66ce1209c4f4.png">

**Comment by phet-steele** [comment]
@arouinfar I immediately liked 1.

**Comment by arouinfar** [comment]
Sounds good @phet-steele. Let's go for (1) as the main screenshot, and then I trust that you'll find appropriate alternates. :)

**Comment by phet-steele** [comment]
Added.
