### ISSUE TITLE
IntroView file is empty

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#76]
Noticed during code review #56. I assume it should be deleted, along with the view folder that it is in.

**Comment by andrey-zelenkov** [comment]
Removed empty IntroView.js file. Git cannot track folders so 'view' folder cannot be removed directly. It must be removed automatically. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks good, closing.
