### ISSUE TITLE
Period Timer behavior seems weird

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#77]
I'm not totally sure if this is an issue or not, since I don't know what the intended behavior of the period timer should be. But, it seems odd to me that you can reset the timer and the button still remains a reset button instead of going back to a play button. Also it is possible to get the timer into a strange state where the button looks like reset, but pressing it starts the timer - as well as the reverse situation where pressing the play button resets it.

It's hard to give exact steps to reproduce, but it happens fairly easily if you just take out the timer and press the button a bunch.

If this is the intended behavior, feel free to let me know. It just seems odd to me and so I want to check if there is a bug here.

**Comment by arouinfar** [comment]
Good catch, @aaronsamuel137. The period timer is not functioning properly.

After playing around with the period timer, I've found a few issues. Some of them are similar to issues that have previously been reported and resolved.
- If the pendulum's motion is stopped using friction, and then the period is recorded, the timer will run infinitely (somewhat similar to the issues reported in #25)
- The timer will malfunction if the period is re-recorded before the trace completely fades away. The path of the period will still trace properly and then fade away, but the the timer will be stuck with display showing 0.0000 s and the reset button will be active (similar to #24). The timer should be able to immediately re-record the period.
- If the reset button is pressed while the period is being recorded, the period trace continues to draw and the timer display shows the time at which the reset button was pressed. The reset button should stop the operation of the period timer -- the display should reset to 0.0000 s, the trace should disappear immediately (not fade), and the reset button should switch back to the start button.



Desired behavior:
Once the start button is pressed, the period will start recording once the pendulum crosses the midline at 0 degrees. The path will be traced while the period is recorded, and then will gradually fade away. While the period is recording, the the start button will turn into a reset button. Once the period has recorded, the reset button will turn back into the start button. If the reset button is pressed while the period is recording, the display will immediately reset to 0s, the trace should disappear (not fade), and the reset button should switch back to the start button.

**Comment by andrey-zelenkov** [comment]
Fixed period timer behavior. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
The previously reported issues appear to be have been fixed, but there are still a few outstanding issues:

- [ ] If the Reset All button is pressed while the period is being recorded, the period trace will continue to draw until the pendulum reaches the midline. The trace remains on screen until the pendulum is displaced, the length or gravity is changed, the period timer is started again, or the browser is refreshed. Clicking on Reset All again does not remove the trace. Reset All should return the screen to its initial state. This issue only exists if more than 1/4 of the period has been traced at the time that Reset All has been clicked.

Just before clicking Reset All (left) and after clicking Reset All (right):
![image](https://cloud.githubusercontent.com/assets/8419308/7711287/d12fa292-fe26-11e4-8ddf-4892da2be77c.png)![image](https://cloud.githubusercontent.com/assets/8419308/7711294/dea9215a-fe26-11e4-8c76-10705416d73e.png)

- [ ] If the period timer is started before the pendulum is displaced, the period will still be traced but the period timer does not record the period. If the period timer is started before the pendulum is displaced, the record button should turn into the reset button and the period should be traced/recorded once the pendulum is put into motion.

After pressing the record button (left) and then displacing the pendulum (right):
![image](https://cloud.githubusercontent.com/assets/8419308/7711671/348ae08e-fe29-11e4-94e8-453c002a9149.png)![image](https://cloud.githubusercontent.com/assets/8419308/7711677/434659f0-fe29-11e4-8ead-23922bf2aa03.png)

Reassigning to @andrey-zelenkov.

**Comment by andrey-zelenkov** [comment]
Fixed period timer behavior for ResetAll button handlers. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
The first issue has been fixed, but the second one is still present. Reassigning to @andrey-zelenkov.

**Comment by andrey-zelenkov** [comment]
Fixed path tracing when period timer is not recording the period. Reassign to @arouinfar for verification.

**Comment by arouinfar** [comment]
Looks great, thanks! Closing.
