### ISSUE TITLE
Use modelViewTransform instead of metersToPixels function

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/pendulum-lab#78]
During code review #56, we noticed two different kinds of transforms:

```js
    // model coordinates are the same as view coordinates
    var modelViewTransform = ModelViewTransform2.createIdentity();
```

And 

```js
    // 1 meter is equal to 175 pixels
    metersToPixels: new LinearFunction( 0, 1, 0, 175 ),
```

It looks like the model coordinates should be in meters and the view coordinates are in "pixels". It would make more sense here to have a model view transform that goes from meters to pixels instead of passing around a function "metersToPixels". Can the metersToPixels function be removed and the modelViewTransform go from meters to screen coordinates?

**Comment by andrey-zelenkov** [comment]
Replace metersToPixels function by modelViewTransform. Reassign to @aaronsamuel137 for verification.

**Comment by aaronsamuel137** [comment]
Looks much better, thanks! Closing
