### ISSUE TITLE
Thermal energy created while sliding variables during swing

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#83]
On the Energy screen, open the energy graph and set the pendulum swinging. After this, changes in length or mass cause a thermal energy build up even though friction is turned off. It helps to slide these variables back and forth quickly and repeatedly. 

![pendla3](https://cloud.githubusercontent.com/assets/5863899/7992693/5a5d9954-0abe-11e5-83b7-b7a33644b7d1.gif)

Tested on Win 8.1

Troubleshooting information:
Name: Pendulum Lab
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.4/pendulum-lab_en.html
Version: 1.0.0-dev.4 2015-06-04 17:46:07 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# pendulum-lab 1.0.0-dev.4 Thu Jun 04 2015 11:46:00 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"7de4a27be4b322b71c5f5046df193a03ccf0f161","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"c7d6ea5f9bef6e3882309af56ad409908dd28878","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"pendulum-lab":{"sha":"2b4cf70e4a8a88b37882b1643d44155a806508ab","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"c9087fbb0cdd83f79452330fec3b83f809e2c0d8","branch":"master"}}

**Comment by arouinfar** [comment]
This is definitely a bug. Changing the mass and/or length should not introduce thermal energy. It looks like this issue is present in the Flash version as well.

**Comment by bryo5363** [comment]
To elaborate on this issue...

When spinning the pendulums extremely fast and with the minimum length, thermal energy will be spontaneously created and then will vanish. 

![recording 8](https://cloud.githubusercontent.com/assets/7717368/8165594/eb0e2ebc-134e-11e5-98d5-d23a28305e3d.gif)

**Comment by ariel-phet** [comment]
Since present in the flash version...we will address

**Comment by jonathanolson** [comment]
Should be no thermal energy now created. Model is accurate to within ~11 digits, AND the thermal energy is not added to at all when friction is off.
