### ISSUE TITLE
Skipping Gravity Values

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#84]
1. On the Lab screen, the sim starts with the gravity at 9.81 and the box above reading "Earth".
2. Click the right arrow until the gravity is 9.92. The box above read "Earth" up until 9.91 (don't think it should) but now reads "Custom" at 9.92.
3. Click left ONCE. The box now reads "Earth" and 9.91. So far this box is contradicting the choice made in phetsims/bending-light/issues/64.
4. Now, click left ONE more time and notice the value jumps from 9.91 to 9.80. I would assume the code believes that the left click in step 3 that changed the box to read "Earth" tricked the sim into thinking it should be at 9.81 even though it displays 9.91, thus one more left click decreases it to 9.80. This happens for the Moon and Jupiter as well. The reverse behaves the same too, jumping from 9.71 to 9.82.

Tested on Win 8.1 FF

Troubleshooting information:
Name: Pendulum Lab
URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.4/pendulum-lab_en.html
Version: 1.0.0-dev.4 2015-06-04 17:46:07 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"comment":"# pendulum-lab 1.0.0-dev.4 Thu Jun 04 2015 11:46:00 GMT-0600 (MDT)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"7de4a27be4b322b71c5f5046df193a03ccf0f161","branch":"master"},"babel":{"sha":"8725cd18114c1307057c465a0762a3cf8f1cb1b9","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"c7d6ea5f9bef6e3882309af56ad409908dd28878","branch":"master"},"dot":{"sha":"a6a50c92c4cda5f8a3371d8c357ea565b7e7bd6c","branch":"master"},"joist":{"sha":"55fd6884039c5ef2f2145093c8530beab5490233","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"pendulum-lab":{"sha":"2b4cf70e4a8a88b37882b1643d44155a806508ab","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"f09eddb7393946fcbedb63ebf6b88d1785c91bfc","branch":"master"},"scenery-phet":{"sha":"7ffc5a1a36e0afe36d035d0367078b3558fd157f","branch":"master"},"sherpa":{"sha":"ae2168a85ceb4094c23cd47ba5fe8145375448eb","branch":"master"},"sun":{"sha":"c9087fbb0cdd83f79452330fec3b83f809e2c0d8","branch":"master"}}

**Comment by arouinfar** [comment]
Good catch, @phet-steele. I've observed this issue in OSX 10.9.5/Chrome 43. The behavior of the gravity slider should match the behavior of the index of refraction sliders in Bending Light. 

* If a tweaker or slider is used to change the gravity from a benchmark (e.g. Earth), "Custom" should immediately be displayed.
* When in Custom mode, "Custom" should ALWAYS be displayed, even if gravity is adjusted to the exact value of one of the other options (e.g. 9.81m/s^2).

**Comment by andrey-zelenkov** [comment]
Fixed gravity values behavior for "custom" body. Reassign to @phet-steele for verification.

**Comment by arouinfar** [comment]
Looks good aside from what is reported in #106, so closing.
