### ISSUE TITLE
iPad 2 iOS 8.3 Performance

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#88]
With an iPad 2, iOS 8.3 (our device labeled Tycho), on the Lab screen I was getting a constant 10 fps in 1.0.0-dev.4.
Things enabled:
1. Two masses, both swinging around 30 degrees
2. Default lengths and masses
3. No friction
4. Velocity checked
5. Acceleration checked
6. Energy graph expanded
7. Gravity maxed at 25.00

Compared to Chrome 43 on Win 8.1: ~35 fps

**Comment by phet-steele** [comment]
Slightly better on iOS 7.1, ~14 fps

**Comment by andrey-zelenkov** [comment]
Made some performance optimizations. Reassign to @phet-steele for verification.

**Comment by jonathanolson** [comment]
I'll investigate this performance as part of https://github.com/phetsims/pendulum-lab/issues/18
