### ISSUE TITLE
Unable to open on iPad 2 iOS 7.0.4

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#89]
Safari keeps crashing every time it tries to load. Tested 1.0.0-dev.4. The sim DOES load on iOS 7.1

**Comment by phet-steele** [comment]
Know issue, @jbphet after making the issue please reference it here.

**Comment by phet-steele** [comment]
Being tracked in phetsims/scenery/issues/434

**Comment by ariel-phet** [comment]
This appears to be due to bugginess in iOS 7.0.4. Closing
