### ISSUE TITLE
Easy to create infinite energy

### ISSUE THREAD

**Issue by bryo5363** [phetsims/pendulum-lab#90]
It is very easy to generate a large amount of energy. In doing this, the various energy values will fluctuate.

Steps to reproduce
1) open energy tab
2) move mass to make it oscillate 
3) reduce the length of the pendulum at the minimum of the trajectory
4) keep repeating

![recording 7](https://cloud.githubusercontent.com/assets/7717368/8016337/7433a4d6-0b9f-11e5-8238-e95c23660710.gif)

**Comment by ariel-phet** [comment]
The minimum length will change when we rescale a few things in the sim, hopefully will address this issue

**Comment by jonathanolson** [comment]
Not sure how changing the minimum length would prevent this, seems more like a design issue to me.

Energy now won't fluctuate with the new model.

If you want to keep energy constant while changing the length, the angle would need to change (if the pendulum is swinging up to 90 degrees on each side, increasing the length at 90 degrees would increase energy).

**Comment by arouinfar** [comment]
Now that @jonathanolson has fixed the model and adjusted the scale/zoom, I don't think there's anything else that needs be done to address this issue. 

> If you want to keep energy constant while changing the length, the angle would need to change (if the pendulum is swinging up to 90 degrees on each side, increasing the length at 90 degrees would increase energy).

It seems unphysical to try to hold energy constant while changing the length, so let's not go there.

Everything looks good to me in dev.6, and the energy no longer fluctuates, so I'll go ahead and close this issue.
