### ISSUE TITLE
Period trace disappears even when sim is paused

### ISSUE THREAD

**Issue by phet-steele** [phetsims/pendulum-lab#96]
@arouinfar, I would add the question label to this but I don't have the permission to on this repo. Would it be more beneficial to keep the period drawn when the sim is paused? It certainly would make more sense.

**Comment by arouinfar** [comment]
Great suggestion, @phet-steele! I agree that it would make more sense for the period trace to remain on screen while the sim is paused. If you pause the sim before the period has been completed, the trace will not fade away (left). However, if the sim is paused <i>after</i> tracing a full period, the trace will fade away (right). 
![image](https://cloud.githubusercontent.com/assets/8419308/8116483/ad278506-103f-11e5-830b-d57a1df43db3.png) ![image](https://cloud.githubusercontent.com/assets/8419308/8116497/ba5a7c1a-103f-11e5-9c4d-cdc5b7f578fc.png)
While the current behavior is consistent with the Flash sim, it would be better if the trace always remains on screen while paused.

**Comment by jonathanolson** [comment]
Looks like this was already fixed.

**Comment by phet-steele** [comment]
> However, if the sim is paused after tracing a full period, the trace will fade away (right).

@arouinfar why?

**Comment by arouinfar** [comment]
@phet-steele I was describing what the Flash sim did. Can't say that I can speak to the motivation there...

I also said
> While the current behavior is consistent with the Flash sim, it would be better if the trace always remains on screen while paused.

I believe the outcome of this issue was supposed to keep the trace from fading away once the sim is paused. However, it looks like that functionality doesn't exist in the latest dev. I'll go ahead and reopen the issue, but I'm not sure who I should assign this to...

**Comment by arouinfar** [comment]
@veillette if this issue is within the scope of your work on Pendulum Lab work, please take care of it.

**Comment by jonathanolson** [comment]
I'll make the "period trace won't continue fading away while the sim is paused" change.

**Comment by jonathanolson** [comment]
Should be implemented.

**Comment by arouinfar** [comment]
👍
