### ISSUE TITLE
Move panels outside of dev boundary when at wider aspect ratios

### ISSUE THREAD

**Issue by arouinfar** [phetsims/pendulum-lab#98]
The playspace would open up quite a bit if the panels could move outside of the dev boundary when at wider aspect ratios.
![screen shot 2015-06-12 at 3 24 38 pm](https://cloud.githubusercontent.com/assets/8419308/8140291/8bf1008c-1117-11e5-8125-a6f8417fb0f1.png)
This has been done in Energy Skate Park: Basics and Charges and Fields. (See https://github.com/phetsims/charges-and-fields/issues/9)

**Comment by ariel-phet** [comment]
@arouinfar - we can have @jonathanolson address this enhancement with other tweaks once MLL is finished

**Comment by jonathanolson** [comment]
@arouinfar, should this basically be handled like bending-light, where the panels move (but only up to a point for extreme window sizes)?

**Comment by arouinfar** [comment]
@jonathanolson, yes let's handle it like Bending Light. Thanks!

**Comment by jonathanolson** [comment]
I changed it so it expands until it has comfortable space to contain the 2m pendulum (don't want to expand further, since otherwise it just means things get farther apart.

**Comment by arouinfar** [comment]
I think it looks great @jonathanolson!
